### ISSUE TITLE
terraform-ls.rootModules removed

### ISSUE THREAD

**Issue by cathex-matt** [hashicorp/terraform-ls#1047]
### Server Version

```
I can't find terraform-ls on my system. I uninstalled the terraform VSCode extension and re-installed, no luck.
First part of the defect.
```

### Terraform Version

```
Terraform v0.15.3
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.2.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Client Version

```
VSCode
Launching language server: ~/.vscode/extensions/hashicorp.terraform-2.24.0-darwin-x64/bin/terraform-ls serve
serve_command.go:101: Starting terraform-ls 0.29.0-dev
```

### Log Output

Insane amount of logs

### Expected Behavior

`terraform.languageServer.rootModules` should be usable. You're completely cluttering VSCode with your extension at the moment.

### Actual Behavior

I can't set anymore the `terraform-ls.rootModules` which should have been migrated to `terraform.languageServer.rootModules` probably. But `terraform.languageServer.rootModules` does not exists.
Do you assume everybody uses a VSCode workspace per project? If yes then that's a wrong assumption.

**Comment by jpogran** [comment]
I'm sorry you're frustrated @cathex-matt, I hope to alleviate your concerns.

It is true that you cannot set `terraform-ls.rootModules` (or `terraform.languageServer.rootModules`) anymore. We announced the deprecation in [v2.20.0](https://github.com/hashicorp/vscode-terraform/blob/main/CHANGELOG.md#2220-2022-04-19) and have started the removal as stated in the breaking changes section of [v2.24.0](https://github.com/hashicorp/vscode-terraform/blob/main/CHANGELOG.md#2240-unreleased).

The original purpose of rootModules was to inform terraform-ls of other locations outside the current workspace to find modules or Terraform files to use for functionality like intellisense and go to definition. With the advent of WSL/Docker/SSH Remote Extensions, Codespaces and web extensions it is increasingly complex to resolve arbitrary paths, when that path could mean different things in different contexts. To further complicate things, users could not use platform specific path segments inside `terraform-ls.rootModules` and share their settings among teammates using different platforms.

Using the VS Code Workspace API, we receive validated, platform agnostic, and fully resolved paths that work with the VS Code trust system that we know will work with terraform-ls. In addition, we receive events when a folder is added to or removed from the workspace that allow us to intelligently update our index of the current environment. We explain a bit more in our readme about [using workspaces](https://github.com/hashicorp/vscode-terraform#vs-code-workspace-support).

Can you expand upon `You're completely cluttering VS Code with your extension at the moment`? I don't know what you mean here.

**Comment by radeksimko** [comment]
We'll document patterns that involve VS Code workspaces as part of https://github.com/hashicorp/vscode-terraform/issues/1221 and continue to gather feedback on how and whether users wish to use that feature and how else we could cater to their needs.

Any upvotes and more detailed feedback is appreciated!

**Comment by cathex-matt** [comment]
Hi,
Thank you both for your answers. I meant that it's difficult following the settings changes on multiple extensions. It makes the VSCode experience rubbish. And it would be great if Microsoft was coming up with a kind of framework to make it smoother, like some kind of extension settings migration one.
