### ISSUE TITLE
Update VS Code installation docs

### ISSUE THREAD

**Issue by dbanck** [hashicorp/terraform-ls#1068]
https://github.com/hashicorp/terraform-ls/blob/main/docs/USAGE.md#vs-code

^ Contains outdated information about the extension and settings

**Comment by tony21921** [comment]
Hi @dbanck, do you mean the configuratoin part, as described in [this document](https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform#terraform-0.11-compatibility)?

**Comment by jpogran** [comment]
No, the part where we describe what extension settings are possbile:

This:

````
"terraform.languageServer": {
    "args": [
        "serve",
    ],
},
```

Should be:

```
"terraform.languageServer.args": [ "serve", ],
```

**Comment by tony21921** [comment]
Thank you. I will work on this.
