### ISSUE TITLE
workspace/didChangeConfiguration notification is not respected for configuring settings

### ISSUE THREAD

**Issue by kittydoor** [hashicorp/terraform-ls#1073]
### Server Version

```
0.28.1
```

### Terraform Version

```
Terraform v1.2.9
```

### Client Version

```
NVIM v0.8.0-dev-1085-g1970d2ac4-dirty (built from git)
```

### Context

When providing `init_options` via nvim-lspconfig, which provides initializationOptions in the initialize request, experimentalFeatures.validateOnSave (or any setting for that matter) works as expected.

When configuring an option using the lspconfig `settings` option, it should be reflected in the language server configuration. This method uses workspace/didChangeConfiguration to deliver the object to the language server.

### Expected Behavior

initializationOptions and workspace/didChangeConfiguration should both allow you to configure the language server.

### Actual Behavior

initializationOptions works, but workspace/didChangeConfiguration is not respected.

**Comment by dbanck** [comment]
Hi @kittydoor 

Thanks for the suggestion. I believe https://github.com/hashicorp/terraform-ls/issues/1008 already covers this, so I'm going to close this as a duplicate to keep the conversation in one place.

**Comment by kittydoor** [comment]
I couldn't find the issue myself, but now that you link it yes, looks like this is a duplicate.

Thanks!
