### ISSUE TITLE
Multiple providers in repository generate huge CPU usage

### ISSUE THREAD

**Issue by Azraeht** [hashicorp/terraform-ls#1119]
### Server Version

```
❯ ~/.vscode/extensions/hashicorp.terraform-2.25.0-linux-x64/bin/terraform-ls --version
0.29.3
```

### Terraform Version

```
❯ terraform -v                              
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/auth0/auth0 v0.40.0
+ provider registry.terraform.io/cyrilgdn/postgresql v1.16.0
+ provider registry.terraform.io/datadog/datadog v3.9.0
+ provider registry.terraform.io/hashicorp/consul v2.15.1
+ provider registry.terraform.io/hashicorp/google v4.44.1
+ provider registry.terraform.io/hashicorp/google-beta v4.44.1
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.5.1
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/hashicorp/vault v2.19.1

Your version of Terraform is out of date! The latest version
is 1.3.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Client Version

VSCode version:
```
❯ code --version     
1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
```
VSCode terraform extension: `2.25.0`

### Terraform Configuration Files

We huse a big repository as workspace containing several hundreds of applications of infrastructure part. Each one defined its is own tf-state.

Here is a example of our repository architecture:
```
└── terraform
    └── env
        ├── internal
        ├── production
        │   ├── app
        │   │   ├── app1
        │   │   ├── app2
        │   │   ├── app3
        │   │   ├── [...]
        │   │   └── app75
        │   └── infra
        │       ├── dns
        │       ├── elasticsearch
        │       ├── kubernetes
        │       ├── [...]
        │       └── network
        └── staging
    └── modules
            ├── module1
            ├── module2
            ├── [...]
            └── module20
```

In each of this folders (e.g `app1`, `elasticsearch` etc...) will defined the needed terraform resources including a `providers.tf`. To avoid drift between the different stack and keep the same providers used everywhere this `providers.tf` file is a symlink to a file present in `production`, `internal`, `staging` folders. With it upgrading a provider on staging will be done by one change in one file and done for all staging terraform states.

### Expected Behavior

When opening VSCode with Terraform Language Server enabled on my repository I expect the IDE to respond well and provides me the right features:
 * Intellisence
 * Syntax validation
 * etc...

### Actual Behavior

When opening my repo, the language server discover all provider references (following symlinks) and took some time one hour or more to walk through them and retrieve their schema. Even if they are all using the same version of providers.

The use of VSCode starts to be very slow and any action (using intellisense for autocompletion, save a file, format a file) triggers the 

We are using around 20 providers in our stack but searching for all providers references following symlink there is more than 3000 items:

Real providers file:
```
❯ find . -type f -name "providers.tf"
./terraform/env/admin/providers.tf
./terraform/env/production/providers.tf
./terraform/env/staging/providers.tf
./terraform/env/internal/providers.tf
./terraform/env/org/providers.tf
```
Example of provider file:
```
❯ cat ./terraform/env/staging/providers.tf
terraform {
  required_providers {
    auth0 = {
      source = "auth0/auth0"
      version = "~> 0.40.0"
    }
    datadog = {
      source  = "datadog/datadog"
      version = "~> 3.9.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 4.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 4.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.1.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 2.0"
    }
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "~> 1.16.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.3.0"
    }
    consul = {
      source  = "hashicorp/consul"
      version = "~> 2.15.1"
    }
  }
  required_version = ">= 0.14"
}
```
References of provider through all stacks:
```
❯ grep -R 'version = ' . | grep providers.tf | wc -l   
3733
```

### Steps to Reproduce

1. Generate a sample repo
```
❯ cat ./generate.sh                                 
#!/bin/bash

ROOTPATH="terraform"
rm -rf $ROOTPATH
mkdir -p $ROOTPATH

# Create envs
for env in production staging internal
do
    mkdir -p $ROOTPATH/$env
	for arch in app infra data
	do
		mkdir -p $ROOTPATH/$env/$arch
		for i in {1..40}
		do
			mkdir -p $ROOTPATH/$env/$arch/$arch$i
			# Create fake stacks
			cat << EOF > $ROOTPATH/$env/$arch/$arch$i/providers.tf
terraform {
  required_providers {
    auth0 = {
      source = "auth0/auth0"
      version = "~> 0.40.0"
    }
    datadog = {
      source  = "datadog/datadog"
      version = "~> 3.9.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 4.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 4.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.1.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 2.0"
    }
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "~> 1.16.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.3.0"
    }
    consul = {
      source  = "hashicorp/consul"
      version = "~> 2.15.1"
    }
  }
  required_version = ">= 0.14"
}
EOF
		done
	done
done
```
2. Open vscode on it `code .`
3. Watch the output of the Terraform extension
4. Check workstation performances
![image](https://user-images.githubusercontent.com/1354360/204481081-25a934e3-d8e8-4037-9ba0-bb558b6f70b1.png)
5. Try to add a resource in any stack (e.g. `terraform/env/production/app/app1` and use Intellisence.

**Comment by dbanck** [comment]
Hi @Azraeht!

Thank you very much for reporting this and even providing a script to generate a workspace similar to yours. That helps a ton in debugging the observed behavior.

Opening the generated workspace in VS Code takes about a minute of CPU time for me on macOS, but I haven't run `terraform init` in any of the directories, which might make a difference.

The `terraform -v` output suggests that you ran `terraform init` for that directory which installs all the providers locally (creating a `.terraform` directory and a `.terraform.lock.hcl` lock file). Is this true for all the 3960 directories? I'm trying to match your workspace as accurately as possible.

I'll also try to reproduce this on Linux to ensure this isn't anything OS-related.

**Comment by radeksimko** [comment]
@Azraeht friendly ping:

> The `terraform -v` output suggests that you ran `terraform init` for that directory which installs all the providers locally (creating a .terraform directory and a `.terraform.lock.hcl` lock file). Is this true for all the 3960 directories?

--- 

In general, indexing thousands of providers will always be a challenge. I would hope that this amount of unique provider versions is not common amongst the LS users, but I frankly don't have any data to prove this (or otherwise to suggest it's common).

**Comment by panekj** [comment]
Most of the CPU is spent in schemas and in malloc. I'll try looking at it closer and make some provisional fix.

**Comment by panekj** [comment]
I've only been able to make slight improvement in the init phase but there is still a problem where terraform-ls gets stuck in eternal loop of requesting schemas for each module. I haven't been able to sit down to deeply study tf-ls code due to other commitments, but hopefully I'll be able to in next few weeks.

**Comment by Azraeht** [comment]
Thanks @panekj for your feedback. On my side I will try to check if it's possible to improve performance with some changes in our repository architecture.

**Comment by 27Bslash6** [comment]
Still a thing. Very annoying.
