### ISSUE TITLE
Missing assets for v0.30.2 release

### ISSUE THREAD

**Issue by cacack** [hashicorp/terraform-ls#1181]
### Server Version
```
v0.30.1
```

### Client Version
```
❯ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Log Output
Upon starting Mason, the following is shown:
```
◍ terraform-ls     ■ new version available: hashicorp/terraform-ls v0.30.1 -> v0.30.2
```

Mason returns the following when attempting to update to the v0.30.2 release:
```
      ▼ Displaying full log
        Downloading file "https://github.com/hashicorp/terraform-ls/releases/download/v0.30.2/terraform-ls_0.30.2_darwin_arm64.zip"...
        ...er/start/mason.nvim/lua/mason-core/managers/std/init.lua:52: Failed to download file "https://github.com/hashicorp/terraform-ls/releases/download/v0.30.2/terraform-ls_0.30.2_darwin_arm64.zip".
        spawn: wget failed with exit code 8 and signal 0. 
```

### Expected Behavior
LSP is updated

### Actual Behavior
LSP fails to update

### Steps to Reproduce
1. Launch NeoVim.
2. Access Mason.
3. Select the terraform-ls LSP module and initiate the update action.

**Comment by cacack** [comment]
Thanks @radeksimko for the quick response!  Looks like I need to open the bug report with the Mason project and not here.  Appears they maintain configs for the various LSP supported..

https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/terraform-ls/init.lua

**Comment by radeksimko** [comment]
Sounds good, let us know if it (the API route) doesn't work for you/Mason and we can try to find a solution.
