### ISSUE TITLE
Missing binary assets in latest release (v0.30.2)

### ISSUE THREAD

**Issue by reegnz** [hashicorp/terraform-ls#1183]
The github release for v0.30.2 does not contain any binary assets.

**Comment by radeksimko** [comment]
Hi @reegnz 
We already discussed the possibility of NeoVim Mason switching to the official Releases API as part of https://github.com/hashicorp/terraform-ls/issues/1181#issuecomment-1433054034

Was there a different use case you had for these assets?

If so, would that use case be satisfied with the Releases API? https://releases.hashicorp.com/docs/api/v1/

**Comment by radeksimko** [comment]
I'd also note that there are other installation methods as documented at https://github.com/hashicorp/terraform-ls/blob/main/docs/installation.md - namely various Linux Packages (RPM, DEB) and Homebrew for macOS/Linux, which should generally be preferred when installing LS on these platforms.

**Comment by reegnz** [comment]
Yeah, my use-case is pretty much Mason for neovim.

**Comment by radeksimko** [comment]
For Mason I'd recommend upvoting/following https://github.com/williamboman/mason.nvim/issues/1001

For asdf - have you considered raising a similar issue upstream? I'm not familiar with asdf myself, but happy to raise an issue and explain things over there as well. That said, AFAICT `asdf` itself does not have builtin support for `terraform-ls`, but there are plugins to provide that, so we'd probably need to reach out to the plugin repo to update this URL? https://github.com/shihanng/asdf-terraform-ls/blob/a4880928a7780a8b7708fe360906415d29347a81/bin/download#LL52

Again - happy to do that myself - just making sure we're on the same page.

Our preference would be to not publish the release assets to another location, but happy to reconsider if the API doesn't work for folks.

**Comment by reegnz** [comment]
Yeah, gonna do that. I closed this issue, as then it is likely gonna be taken care of on the Mason side.
