### ISSUE TITLE
GitHub release 0.30.2 is missing binaries and checksums

### ISSUE THREAD

**Issue by ilkka** [hashicorp/terraform-ls#1188]
Looks like the latest GitHub release only has the sources. It's not been created by GitHub actions, maybe that's why? Just noticed this because I have a personal Scoop manifest with autoupdate functionality and this breaks it.

**Comment by ilkka** [comment]
Ah, okay, probably this is intentional since I see Waypoint's changed in the same exact way, and the files seem to be in releases.hashicorp.com.

**Comment by radeksimko** [comment]
Hi @ilkka 
Yes, we encourage everyone to use the releases.hashicorp.com endpoint which also has its own documented API at https://releases.hashicorp.com/docs/api/v1/

I hope that works for the use case you mentioned? i.e. Scoop manifest auto-update? Let me know if it doesn't.

**Comment by ilkka** [comment]
Oh yeah, just changed some URL patterns and my manifests work again. Thanks!
