### ISSUE TITLE
Assets missing for 0.30.2 release

### ISSUE THREAD

**Issue by technicallyjosh** [hashicorp/terraform-ls#1189]
Hello there 👋🏼

I noticed that the release for [0.30.2](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.2) is missing all the binaries for platforms. This breaks LSP installs in various tooling. Here is an example failure in mason LSP in nvim:
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/8335467/220034250-8594ffce-1430-457f-bbea-9aa3a3e36695.png">

e.g. It's looking for `https://github.com/hashicorp/terraform-ls/releases/download/v0.30.2/terraform-ls_0.30.2_darwin_arm64.zip` but it's missing 😓.

Previous versions have all the proper assets for download. e.g. [0.30.1](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.1)

**Comment by radeksimko** [comment]
Hi @technicallyjosh 
Have you tried updating Mason?

The latest version should be pulling updates from releases.hashicorp.com which is where we continue to publish our artifacts.

See https://github.com/williamboman/mason.nvim/pull/1002

**Comment by technicallyjosh** [comment]
Ah thanks much for the info. Looked like something missed when releasing since it didn't look like the other releases. Will update Mason.
