### ISSUE TITLE
v0.30.2 release does not include ZIP files with terraform-ls binaries

### ISSUE THREAD

**Issue by jwadolowski** [hashicorp/terraform-ls#1191]
### Server Version

N/A

### Terraform Version

N/A

### Client Version

Neovim

### Terraform Configuration Files

N/A

### Log Output

N/A

### Expected Behavior

[v0.30.2 release page](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.2) should provide links to precompiled binaries just like any former release (i.e. [v0.30.1](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.1))

### Actual Behavior

404 during terraform-ls upgrade:

https://github.com/hashicorp/terraform-ls/releases/download/v0.30.2/terraform-ls_0.30.2_darwin_amd64.zip

### Steps to Reproduce

Just compare [v0.30.2](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.2) release page with [v0.30.1](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.1) one

**Comment by radeksimko** [comment]
Hi @jwadolowski 
Do you use Mason to manage your LS installation? If so, have you tried updating it?
The latest version should be pulling updates from releases.hashicorp.com which is where we continue to publish our artifacts.

See https://github.com/williamboman/mason.nvim/pull/1002

Was there a different use case you had for these assets? If so, would that use case be satisfied with the Releases API? https://releases.hashicorp.com/docs/api/v1/

**Comment by jwadolowski** [comment]
Hey @radeksimko! That's correct, I use Mason for LS management.

Thanks for pointing me to https://github.com/williamboman/mason.nvim/pull/1002. That solves the problem for me :)

**Comment by jonathanio** [comment]
This doesn't seem to have worked. v0.30.3 doesn't have any binary assets either.

**Comment by jonathanio** [comment]
@radeksimko sorry. I'm the maintainer for the `terraform-ls-bin` on Arch Linux. I was expecting them to be available. I'll update the packaging process to take this into account. Thanks for the feedback.

**Comment by radeksimko** [comment]
@jonathanio Understood - there is also API https://releases.hashicorp.com/docs/api/v1/ but the assets should generally all have predictable URLs. Let us know (preferably in a new issue) if you run into problems and we'd be happy to help.

Thank you for the maintenance of the package btw.!
