### ISSUE TITLE
Missing assets for GitHub releases

### ISSUE THREAD

**Issue by sudomateo** [hashicorp/terraform-ls#1195]
The following `terraform-ls` versions do not have any downloadable assets (e.g. `terraform-ls_0.30.3_linux_amd64.zip`) under the [releases page](https://github.com/hashicorp/terraform-ls/releases).

- [v0.30.3](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.3)
- [v0.30.2](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.2)

This makes automated tooling such as [williamboman/mason.nvim](https://github.com/williamboman/mason.nvim) unable to update `terraform-ls` to the latest release since it pulls assets from GitHub releases.

The latest release with downloadable assets is [v0.30.1](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.1).

**Comment by radeksimko** [comment]
Hi @sudomateo 
Mason was updated recently to account for the change in our release process.
https://github.com/williamboman/mason.nvim/pull/1002

If you use Mason, updating it should resolve the issue. If you have any other tooling which previously relied on assets hosted on GitHub, I'd explore the possibility of switching that to https://releases.hashicorp.com/terraform-ls/ and/or the [API](https://releases.hashicorp.com/docs/api/v1/).

**Comment by sudomateo** [comment]
Awesome! I was unaware of the switch. Thank you and sorry for the noise.
