### ISSUE TITLE
Add completion and hover support for built-in / reserved blocks/attributes

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#121]
This TF version specific potentially (ie. `for_each`).

Providers:

- [ ] `alias`
- [ ] `version` (is this 0.12 only? not sure if it still exists in 0.13)

Resources:

- [ ]  `depends_on`
- [ ]  `count`
- [ ] `for_each`
- [ ] `provider`
- [ ] `lifecycle`
  - [ ] `create_before_destroy`
  - [ ] `prevent_destroy`
  - [ ] `ignore_changes`
- [ ] `provisioner`
- [ ] `connection`

Data Sources:

- [ ]  `depends_on`
- [ ]  `count`
- [ ] `for_each`
- [ ] `provider`

Additional top level blocks:

- [ ] `terraform`
- [ ] `variable` #122 
- [ ] `output` #123 
- [ ] `backend`

**Comment by radeksimko** [comment]
I'm happy to track this as a tickable list, just FYI that all of the above depends on https://github.com/hashicorp/terraform-ls/issues/36 - i.e. having a proper parser for blocks which don't have an explicitly "parseable" schema.
