### ISSUE TITLE
Add build environment details to version output

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#127]
### Current Version

```
v0.2.1
```

### Use-cases

As mentioned in https://github.com/hashicorp/terraform-ls/issues/88 there are cases when user may decide to compile the language server in their own environment.

While custom-compiled binaries and bugs stemming from differences in build environment should be fairly uncommon, they do exist and can be challenging to debug. As mentioned in the linked thread Go itself does not provide ways of prescribing the build environment yet - e.g. there is no way of guaranteeing what Go version, compiler (cgo/gc), nor compilation flags will be used.

Maintainers should at least have an easy way of discovering custom builds to aid with initial issue triaging and debugging.

### Attempted Solutions

Enforce building via makefile, which breaks cross-platform compatibility and can appear unnatural to seasoned Go developers who are used to run just native `go build/install`. It also enforces testing via makefile, which is suboptimal.

### Proposal

Add details about build environment to `version` output, e.g.

```
v0.2.1-dev
go1.14.3 darwin/amd64 (compiler: gc)
```

**Comment by radeksimko** [comment]
@aeschright I think this would likely break the logic here https://github.com/hashicorp/vscode-terraform/blob/1c882b35bb52e834214fad186c167f8ecaf04804/src/languageServerInstaller.ts#L33 - it may be worth just cutting out the first line of output, alternatively you could wait for https://github.com/hashicorp/terraform-ls/issues/184

**Comment by aeschright** [comment]
I think getting the JSON output in first would be my preference.

**Comment by radeksimko** [comment]
As mentioned in https://github.com/hashicorp/terraform-ls/pull/341#discussion_r551386550 we should also consider reporting whether, or perhaps when particular `go generate` ran.
