### ISSUE TITLE
E5248: Invalid character in group name

### ISSUE THREAD

**Issue by rgruyters** [hashicorp/terraform-ls#1316]
### Language Server Version

v0.31.3

### Terraform Version

Terraform v1.5.0 on darwin_amd64

### Client Version

NVIM v0.9.1

### Terraform Configuration

```terraform
name = "foo"
flavor_name = "m1_c2_m16_d20"
```

### Steps to Reproduce

- save the [minimal.lua](https://gist.github.com/rgruyters/976cbf60c393dee6582c9b0619f35093) config to `/tmp/minimal.lua`
- Open a terraform.tfvars file with `nvim -nu /tmp/minimal.lua terraform.tfvars`

### Expected Behavior

No error messages

### Actual Behavior

E5248: Invalid character in group name
E5248: Invalid character in group name
E5248: Invalid character in group name
E5248: Invalid character in group name
..

### Gist

https://gist.github.com/rgruyters/507c28a5e55f66b944c7cd5ecca7be28

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @rgruyters 
Would you mind providing some further context to the "actual behaviour", e.g. where exactly do you see "E5248: Invalid character in group name" ?

I looked at the attached log and it doesn't contain anything out of ordinary (nor the mentioned error). I cannot think of any component of the language server that could directly produce such an error/diagnostic.

**Comment by rgruyters** [comment]
The message is displayed in the editor. (in my case Neovim)

**Comment by rgruyters** [comment]
Small update, I have tested with older versions of terraform-ls (up-to v0.30.x), but issue is still there. Because I use the nvim-lspconfig plugin, for loading LSP, I have downgraded to an older version of this plugin and the message is gone.

Looks like the issue is with nvim-lspconfig. I will post an issue in their repo
