### ISSUE TITLE
Support submodules

### ISSUE THREAD

**Issue by lfdominguez** [hashicorp/terraform-ls#136]
Hello i have a Terraform deploy that use submodules, I'm using OpenStack provider, but is recognized on root main.tf, but on any submodule doesnt recognize the openstack resources on Language Server.
On root:
![image](https://user-images.githubusercontent.com/5604131/69908042-600eab00-13af-11ea-95c1-ced02cd5fbd3.png)

On any submodule
![image](https://user-images.githubusercontent.com/5604131/69908046-787ec580-13af-11ea-951e-d15fc7782dd0.png)

**Comment by radeksimko** [comment]
You are right, this is not supported yet, but it makes sense to support it. 

https://github.com/hashicorp/terraform-ls/issues/32 is the canonical issue where we track this, so I'm going to close this one, but I would really welcome some details about your provider configuration/inheritance there, so we can assess how to best support these use cases.
