### ISSUE TITLE
Completion requests not working for provider resources

### ISSUE THREAD

**Issue by vincer** [hashicorp/terraform-ls#1367]
### Language Server Version

0.31.4

### Terraform Version

v1.5.6

### Client Version

VSCode Terraform v2.27.1

### Terraform Configuration

```terraform
terraform {

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.14"
    }
  }
}

provider "aws" {
}
```

### Steps to Reproduce

1. Create new workspace with main.tf with the above config.
2. `terraform init`
3. Type `resource "` (or `resource "aws`) and invoke completion/intellisense.

### Expected Behavior

Get a list of AWS provider resources (e.g. `aws_instance`, `aws_db_instance`, etc.)

### Actual Behavior

No AWS provider resources are listed.

<img width="919" alt="Screenshot 2023-08-29 at 12 14 13 PM" src="https://github.com/hashicorp/terraform-ls/assets/792368/bbc36e18-1920-46e4-a5e7-2f1f49c5f0fd">
<img width="1035" alt="Screenshot 2023-08-29 at 12 14 21 PM" src="https://github.com/hashicorp/terraform-ls/assets/792368/a5158369-ada8-4ac2-a539-b49f6f6e2434">

### Gist

https://gist.github.com/vincer/20cb64ba05517d8a842056f65d0df02e

### Workarounds

No workaround found.

I've tried debugging myself but have hit a wall. My best lead is that I see multiple repeated lines in terraform-ls output about getting the provider schema:
```
2023/08/29 12:14:09 provider_schema.go:282: PSS: getting provider schema (/Users/vince/test, registry.terraform.io/hashicorp/aws, ~> 5.14)
2023/08/29 12:14:09 provider_schema.go:282: PSS: getting provider schema (/Users/vince/test, registry.terraform.io/hashicorp/aws, ~> 5.14)
2023/08/29 12:14:09 provider_schema.go:282: PSS: getting provider schema (/Users/vince/test, registry.terraform.io/hashicorp/aws, ~> 5.14)
2023/08/29 12:14:09 provider_schema.go:282: PSS: getting provider schema (/Users/vince/test, registry.terraform.io/hashicorp/aws, ~> 5.14)
```

But in the terraform log file (which is at the bottom of the gist) I see no calls to terraform to get the schema (i.e. no `terraform providers schema -json`). I do see calls for `terraform version` and `fmt`, so I know that log is working.

On the other hand, once I'm in an `aws_instance`, I do see completion options for relevant fields like `ami`. But the `Prefill Required Fields` doesn't seem to be working either anywhere which I'm not sure is related.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @vincer 
Thank you for a detailed bug report.

This is unfortunately a known issue we already track under https://github.com/hashicorp/terraform-ls/issues/57 Addressing it will require some changes in the upstream HCL parser we leverage in the language server.
