### ISSUE TITLE
Package terraform-ls-0.31.5-1.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by jamielinux** [hashicorp/terraform-ls#1391]
### Language Server Version

0.31.4

### Terraform Version

Terraform v1.5.6 on linux_amd64

### Client Version

NVIM v0.9.1

### Terraform Configuration

```dosini
[hashicorp]
name=Hashicorp Stable - $basearch
baseurl=https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://rpm.releases.hashicorp.com/gpg

[hashicorp-test]
name=Hashicorp Test - $basearch
baseurl=https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/test
enabled=0
gpgcheck=1
gpgkey=https://rpm.releases.hashicorp.com/gpg
```

### Steps to Reproduce

I get the problem when running `dnf update` on Fedora 38. The `terraform-ls` package is already installed at package version `0.31.4-1`.

I suppose the steps to reproduce from scratch would be:

1. `sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo`
2. `sudo dnf install -y terraform-ls`

### Expected Behavior

When running `dnf update -y`, the `terraform-ls` package should be updated.

### Actual Behavior

```console
# dnf update terraform-ls -y
Last metadata expiration check: 0:00:24 ago on Wed 06 Sep 2023 21:12:35 BST.
Dependencies resolved.
==================================================================================
 Package               Architecture    Version           Repository          Size
==================================================================================
Upgrading:
 terraform-ls          x86_64          0.31.5-1          hashicorp           14 M

Transaction Summary
==================================================================================
Upgrade  1 Package

Total size: 14 M
Downloading Packages:
[SKIPPED] terraform-ls-0.31.5-1.x86_64.rpm: Already downloaded
Package terraform-ls-0.31.5-1.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

I did already try `dnf clean all` and trying again.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Thank you for the report. I'm able to reproduce the error

**Comment by dbanck** [comment]
The artifacts have been resigned and republished. Installation/update should work now:

```
...
Running transaction
  Preparing        :                                                                                  1/1
  Installing       : openssl-1:3.0.9-2.fc38.x86_64                                                    1/2
  Installing       : terraform-ls-0.31.5-1.x86_64                                                     2/2
  Running scriptlet: terraform-ls-0.31.5-1.x86_64                                                     2/2
  Verifying        : openssl-1:3.0.9-2.fc38.x86_64                                                    1/2
  Verifying        : terraform-ls-0.31.5-1.x86_64                                                     2/2

Installed:
  openssl-1:3.0.9-2.fc38.x86_64                        terraform-ls-0.31.5-1.x86_64

Complete!
```

I'm going to close this for now, but if this is still an issue please respond and we'll re-open.
