### ISSUE TITLE
v2.0.0-rc.1 is "Unable to retrieve schema: executable file not found" if provider is defined

### ISSUE THREAD

**Issue by laugmanuel** [hashicorp/terraform-ls#140]
### Server Version
```
❯ ./terraform-ls --version
0.3.1
```

### Terraform Version
```
❯ terraform -v
Terraform v0.12.26
+ provider.azurerm v2.11.0
```

### Client Version
```
VSCode: 1.45.1
Terraform Plugin: 2.0.0-rc.1
Terraform-ls: 0.3.1
Azure-cli: 2.6.0
Terraform: 0.12.26
```

### Terraform Configuration Files

```hcl
# DOES NOT WORK
terraform {
  backend "azurerm" {
    storage_account_name = "<storage account name>"
    container_name       = "tfstate"
    key                  = "test.terraform.tfstate"
    resource_group_name  = "tfstate"
  }
}

provider "azurerm" {
  version = "~> 2"
  features {}
}
```

```hcl
# DOES WORK
terraform {
}

provider "azurerm" {
  version = "~> 2"
  features {}
}
```

### Log Output
https://gist.github.com/laugmanuel/f63f67ab57f0e82f23f4fac541a60981

### Expected Behavior
The language server should be able to retrieve the schema, even when I use a specific backend for state.

### Actual Behavior
If the `azurerm` backend is configured the language server fails to retrieve the schema with:
```
2020/06/05 16:53:53 schema_storage.go:116: error obtaining schemas: Unable to retrieve schemas: failed to get schemas: terraform (pid 48583) exited (code 1): exit status 1
stdout: ""
stderr: "\x1b[31m\n\x1b[1m\x1b[31mError: \x1b[0m\x1b[0m\x1b[1mError building ARM Config: Error loading the Profile Path from the Azure CLI: exec: \"sh\": executable file not found in $PATH\x1b[0m\n\n\x1b[0m\x1b[0m\x1b[0m\n"
```

### Steps to Reproduce
- Login to Azure in using `az login`
- Create a storage account and a blob container
- Use the `azurerm` backend to store state in that storage account
- Run `terraform init`
- Open Code and watch the output of `terraform-ls``

**Comment by radeksimko** [comment]
Hi @laugmanuel 
thank you for the detailed report and for helping us test the early rc version of the extension!

Two questions:
1. Can you try running `terraform providers schema -json` in your terminal? Does it also result in the same error (`exec: "sh": executable file not found in $PATH`)? If it doesn't, then chances are that VSCode and/or Terraform isn't receiving the same environment variables. If it does, then I think there's something wrong with the authentication in general.
2. Am I right that you're running on macOS (guessing based on the paths in log file)?

**Comment by laugmanuel** [comment]
Regarding your questions:
1. Running the command in a separate shell works as expected and returns a lot of information. Using `az` or `terraform` in this shell also works like it should
2. Yes, it's a MacOS system

The `az` binary is located at `/use/local/bin` if that helps

**Comment by radeksimko** [comment]
Can you try to upgrade to the latest LS (0.3.2) which I released just moments ago? It contains a bugfix which should help pass through environment variables - which may be relevant here.

**Comment by laugmanuel** [comment]
Thanks for the great support.
I can confirm that 0.3.2 does indeed work and gets the schema.

I'll close this issue then 👍
