### ISSUE TITLE
Show details of attributes of a resource

### ISSUE THREAD

**Issue by esn89** [hashicorp/terraform-ls#1415]
### Description

Right now, when I do a hover, it shows:

<img width="424" alt="Screenshot 2023-09-18 at 1 32 31 PM" src="https://github.com/hashicorp/terraform-ls/assets/1475220/a06c9c86-d1ba-454b-9c70-0ab4695bf701">

I was wondering, if it is possible to have it show the full blurb and description as per the documentation online:

> (Optional) A value that indicates whether the DB cluster has deletion protection enabled. The database can't be deleted when deletion protection is enabled. By default, deletion protection is disabled.

### Links

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster#deletion_protection

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

Maybe there is already such a function already and I'm not aware on how to set it?  Guidance would be appreciated.

**Comment by radeksimko** [comment]
Hi @esn89
This is already how it works, as can be demonstrated on some other providers:

![2023-09-20 08 02 18](https://github.com/hashicorp/terraform-ls/assets/287584/bb858657-8a59-4085-9c3b-cddb7aa5ce1d)

The only issue affecting the example you attached is that the AWS provider does not include the description inside the provider code/schema, i.e. the linked documentation is currently a "decoupled" markdown file which the language server does not access.

To be more specific, there would have to be `Description` included in [here](https://github.com/hashicorp/terraform-provider-aws/blob/701f0913d5eb8ce1d845b46fc4e8adbfdad6435d/internal/service/docdb/cluster.go#L265-L268).

On a slightly positive note, the team maintaining the provider seems to be aware and tracks this under https://github.com/hashicorp/terraform-provider-aws/issues/28888 so I would encourage you to perhaps upvote, subscribe and/or comment there.

**Comment by esn89** [comment]
@radeksimko , you're right!  I see it for GCP.  Thank you very much for your explanation.
