### ISSUE TITLE
textDocument/completion: Provide completion for variable / local / datasource within string interpolation

### ISSUE THREAD

**Issue by AnhQuanTrl** [hashicorp/terraform-ls#1455]
### Language Server Version

v0.32.1

### Problem Statement

Within a string interpolation `${data.}`, currently if the server receives a `textDocument/completion` request, it will return an empty list of items even if a data source has been defined. The server also return nothing for variable and locals.
For local / variable / data source outside string interpolation, auto completion works. It would be nice to add this capability to the server.

### Attempted Solutions

```tf
module "service" {
  source = "..."
  # auto complete works here
  environment = var.environment

  # auto complete does not work here
  some_property = "${var.environment}" 
}

data "aws_ssm_parameter" "param" {
  name = "..."
}
```

### Related LSP methods

- textDocument/completion

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @AnhQuanTrl 
We already track this enhancement under https://github.com/hashicorp/terraform-ls/issues/522 so I'm going to close this as a duplicate to keep conversation in one place.

Thanks.
