### ISSUE TITLE
auto_enable attribute of aws_guardduty_organization_configuration demanded

### ISSUE THREAD

**Issue by StorageMatt** [hashicorp/terraform-ls#1471]
### Language Server Version

I assume the latest

### Terraform Version

Terraform v1.5.7 on darwin_arm64

### Client Version

VSCode HashiCorp Terraform v2.28.2

### Terraform Configuration

```terraform
resource "aws_guardduty_organization_configuration" "org_guardduty_autoenable_ew2" {
  depends_on = [aws_guardduty_organization_admin_account.org_guardduty_admin_ew2]
  provider   = aws.sec-serv-prod-ew2

  auto_enable_organization_members = "NEW"
  detector_id                      = aws_guardduty_detector.guardduty_detector_ew2.id

  datasources {
    s3_logs {
      auto_enable = true
    }
    kubernetes {
      audit_logs {
        enable = true
      }
    }
  }
}
```

### Steps to Reproduce

Just drop the above in VSCode with the latest version of Hashicorp Terraform and the syntax highlighter gets very grumpy - Required attribute "auto_enable" not specified: An attribute named "auto_enable" is required here
- Unexpected attribute: An attribute named "auto_enable_organization_members" is not expected here

### Expected Behavior

That it's completely cool with auto_enable_organization_members

### Actual Behavior

It's not at all cool with auto_enable_organization_members and instead wants `auto_enable = xxx` which according to the docs is the deprecated style.

### Workarounds

Ignore it.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by StorageMatt** [comment]
Apologies for the very delayed response, I've been away from work for a while.
Anyway, I've initialized again this morning and had a look and interestingly, VSC is flagging only the files in the .terragrunt-cache directory as being incorrect and when I mouse over, it's showing that it's using AWS provider v4.67.0. So fair enough that it's showing an error maybe, but I have initialized using the latest version of AWS provider (5.23.0) and all cache files confirm this. So any idea why the LS is using 4.67.0 in this context?

**Comment by radeksimko** [comment]
Thanks for those extra details.

Can you check what versions and constraints are being detected by the LS/extension in the panel?
![Screenshot 2023-11-14 at 13 51 36](https://github.com/hashicorp/terraform-ls/assets/287584/5d96a293-1e9f-4259-a27b-d3407cd7a971)

Secondly, can you double check what LS version is being detected in the bottom bar?

![Screenshot 2023-11-14 at 13 54 22](https://github.com/hashicorp/terraform-ls/assets/287584/d5088aa4-3911-48ce-9e0c-65753af3278e)

Lastly, can you try reloading VS Code via the command palette?
![Screenshot 2023-11-14 at 13 55 18](https://github.com/hashicorp/terraform-ls/assets/287584/1c77ee82-7c77-446e-bcad-00cb8a99ab53)

Normally, changes in `.terraform` (which includes installation of providers, as done by `terraform init`) are detected automatically. If it's not then this would suggest a bug in the detection.
