### ISSUE TITLE
Add configuration option for remote development

### ISSUE THREAD

**Issue by bytebeast** [hashicorp/terraform-ls#1490]
### Language Server Version

0.32.3

### Problem Statement

My current work workflow is develop on laptop, commit , push and then run a job that runs TF on dev env or prod env. So I never run terraform on my laptop. Would like a way to disable the errors that are not relevant in this dev environment. Like:

* Module not installed ... run terraform init
* etc... 

and keep others that are, like:

* Unexpected block, blocks of type "foo" not expected here.

It would be nice to have a configuration boolean flag that disables errors that expect terraform is running on laptop.

### Attempted Solutions

n/a

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @bytebeast,

There are two sources for the diagnostics you're referring to:

### `terraform validate`
This will always require a local Terraform and provider/module installation. So you would have to run `terraform init` to be able to use it.

Running `terraform validate` on save is controlled via a setting and can be turned off:

```json
  "terraform.experimentalFeatures.validateOnSave": false,
```

### Enhanced Validation
This feature will run a set of validators against your configuration without requiring a Terraform installation. Here is a list of the included validators: https://github.com/hashicorp/terraform-ls/blob/main/docs/validation.md#enhanced-validation

Sounds like you'll want to leave this feature on, but just in case, here's the configuration to turn it off:
```json
  "terraform.validation.enableEnhancedValidation": false,
```

Let me know if this solves your problem or if you need more fine-grained control. For example, we track settings for individual validators in https://github.com/hashicorp/vscode-terraform/issues/1605.

**Comment by bytebeast** [comment]
This is exactly what I wanted. Thanks!

**Comment by jpogran** [comment]
@bytebeast In case you were unaware, you can add both those settings to the VS Code machine config scope so that they activate when in a remote development environment, but not when run on the host. Just in case you need to run locally in the future.
