### ISSUE TITLE
Auth and other environment variables

### ISSUE THREAD

**Issue by JuanSeBestia** [hashicorp/terraform-ls#154]
I use `GOOGLE_APPLICATION_CREDENTIALS` env variable to retrive all information of backend gcs, how to put this variable inside the server terraform-ls.

When it run, show error

```
2020/06/11 09:28:06 schema_storage.go:116: error obtaining schemas: Unable to retrieve schemas: failed to get schemas: terraform (pid 8829) exited (code 1): exit status 1
stdout: ""
stderr: "\x1b[31m\n\x1b[1m\x1b[31mError: \x1b[0m\x1b[0m\x1b[1mstorage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.\x1b[0m\n\n\x1b[0m\x1b[0m\x1b[0m\n"
```

**Comment by paultyng** [comment]
You can alternatively execute Terraform via a wrapper script, here are instructions how to do that as a workaround: https://github.com/hashicorp/vscode-terraform/wiki/Manually-Setting-the-Terraform-Executable-Path

**Comment by paultyng** [comment]
I'm going to consolidate this with #142, they seem to be the same issue (with different backends) so would most likely be solved by the same fix.
