### ISSUE TITLE
terraform-ls fails to start when I open a Terraform project from WSL with VScode

### ISSUE THREAD

**Issue by Ernyoke** [hashicorp/terraform-ls#1585]
### Language Server Version

v0.32.5

### Terraform Version

Terraform 1.3.4

### Client Version

VSCode 1.85.1

### Terraform Configuration

```terraform
No relevant configuration required.
```

### Steps to Reproduce

Prerequisites:

- WSL v1 (I cannot migrate to v2 for reasons which are not relevant here)
- Ubuntu distribution installed for WSL
- Visual Studio Code configured to be opened from WSL with `code` command.
- HashiCorp Terraform plugin is installed (v2.29.2) for VSCode

1. Create a Terraform project in the `home` folder.
2. Open it with Visual Studio Code using the `code` command.

### Expected Behavior

The project opens correctly with no issue, errors.
terraform-ls is starting up correctly.

### Actual Behavior

terraform-ls fails to start with the following output in the logs:

```
2024/01/17 14:51:45 rpc_logger.go:48: Error for "initialize" (ID 0): [-32602] Unsupported or invalid URI: "file://wsl.localhost/Ubuntu-20.04/home/ervin/aws-ops-monitoring-alerting" This is most likely client bug, please report it.
2024/01/17 14:51:45 opts.go:215: Completed 1 requests [107.9516ms elapsed]
Failure to start terraform-ls. Please check your configuration settings and reload this window
Client: Starting --> Stopped
[Error - 2:51:45 PM] terraform client: couldn't create connection to server.
  Message: Unsupported or invalid URI: "file://wsl.localhost/Ubuntu-20.04/home/ervin/aws-ops-monitoring-alerting" This is most likely client bug, please report it.
  Code: -32602 
INVALID_URI_WSL
```

### Workarounds

No workaround discovered yet.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
Hey @Ernyoke, thanks for the detailed report. I have used this extension in the past with WSL 1 and 2, and confirm it working.

I see that you're opening VS Code from the `code` command, which is good, but from which shell are you doing so? This matters as it determines whether VS Code starts inside the WSL instance or just attempts to use a UNC path.

You've probably already read this, but as shown in the [docs](https://code.visualstudio.com/docs/remote/wsl#_open-a-remote-folder-or-workspace) you need to open a WSL terminal window either by opening the WSL bash terminal directly or by typing `wsl` in a PowerShell or cmd terminal, then navigate to the folder and type `code .` Alternatively you can do this inside VS Code, as shown in that link.

That should resolve your issue. If not, could you check that the extension is installed in the `Local` section of the Extension Bar?

**Comment by Ernyoke** [comment]
Hi @jpogran ,

I'm using bash with Ubuntu 20.04.

I did record my screen in order to show you exactly what I'm doing:
https://youtu.be/PBpJh_CMelA

Essentially, I'm opening a shell from Windows Terminal and after I open a terraform project with `code .` command.

"That should resolve your issue. If not, could you check that the extension is installed in the Local section of the Extension Bar?" 
Could you provide a bit more information what do you mean by this? `terraform-ls` is installed as part of Hashicorp's Terraform plugin (https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform) .

This plugin worked as expected until 16th of January when the newest version of this plugin (v2.29.2) was rolled out.

**Comment by kahawai-sre** [comment]
I have the same issue with WSL 2, ubuntu. Have used this for a long time without this issue on a different environment. Set up new laptop/environment 
Ext v2.29.2
![image](https://github.com/hashicorp/terraform-ls/assets/77031653/e40d6b71-461d-4b4b-a3ec-036da428b1ae)

**Comment by Ernyoke** [comment]
Hi @kahawai-sre,

I found that a temporary workaround would be to revert to the previous version of the Hashicorp's Terraform extension:
![Revert to previous version](https://github.com/hashicorp/terraform-ls/assets/5096852/73f725c6-fc8f-4222-b8f9-60a8e96a7180).

For me v2.29.1 works just fine.

**Comment by jpogran** [comment]
Thanks everyone for your additional feedback. We've decided to revert https://github.com/hashicorp/terraform-ls/pull/1522, which was intended to help users use the correct way to start WSL. It's causing more harm than help, so we're reverting it and will revisit the detection method.

This has been revereted and released in both the latest terraform-ls and vscode-terraform versions.

**Comment by Ernyoke** [comment]
Hi @jpogran, @dbanck,

I can confirm that this is fixed with the latest update.

Thank you for your help. 

Regards,
Ervin
