### ISSUE TITLE
Module autocomplete does not work on root module with private git repo as source

### ISSUE THREAD

**Issue by Jahsis** [hashicorp/terraform-ls#1604]
### Language Server Version

v0.32.6

### Terraform Version

Terraform v1.4.7 on linux_amd64

### Client Version

NVIM v0.9.5

### Terraform Configuration

```terraform
module "cluster" {
  source = "git@github.com:<org>/<repo>.git//common/eks?ref=v123"

  name = "cluster1"
}

resource "aws_security_group_rule" "https" {
  type                     = "ingress"
  from_port                = 443
  to_port                  = 443
  protocol                 = "tcp"
  security_group_id        = "<sg_id>"
  source_security_group_id = module.cluster.sg_id
}
```

### Steps to Reproduce

1. Navigate to infrastructure folder.
2. Run `terraform init` to initialize environment.
3. Open main.tf file, navigate to `source_security_group_id = module.cluster.sg_id` line, remove `module.cluster.sg_id` part and start writing `module.`

### Expected Behavior

After typing `module.` auto completion should suggest to enter `cluster` as module name.

### Actual Behavior

It does not suggest module auto completion. Manually entering `module.cluster.` module outputs also is not suggested.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
We have just released a new version of vscode-terraform: [2.32.0](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.32.0) which adds support for private git repositories (for initialized environments). The update should show up automatically in VS Code.

I'm closing this issue as completed. In case you experience any problems, please do let us know.
