### ISSUE TITLE
Support Terraform Test (*.tftest.hcl) Files

### ISSUE THREAD

**Issue by bgshacklett** [hashicorp/terraform-ls#1648]
### Language Server Version

0.32.6+Homebrew

### Problem Statement

Terraform now supports testing configurations using `.tftest.hcl` files as test descriptions. It would be helpful if terraform-ls supported these files so that the features of the LSP were available while writing tests.

### Attempted Solutions

n/a

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
We are tracking this as a meta issue in the vscode-terraform repository: https://github.com/hashicorp/vscode-terraform/issues/1534.

If this lands, it will definitely be supported in all editors with LSP support. We just had to pick a repository for our meta issues and went with the one where people usually land, which may make it a bit hard to discover for non-vscode users. Sorry about that.

I'll close this as a duplicate for now.
