### ISSUE TITLE
Error for "initialize" (ID 1): [-32098] '' expected a map, got 'slice'

### ISSUE THREAD

**Issue by brw** [hashicorp/terraform-ls#1655]
### Language Server Version

v0.32.7

### Terraform Version

Terraform v1.7.4 on linux_amd64

### Client Version

Neovim v0.9.5

### Terraform Configuration

```terraform
terraform {}

# Happens with any file, no matter what's in it
```

### Steps to Reproduce

1. Open any .tf file in Neovim with terraform-ls configured as described [here](https://github.com/hashicorp/terraform-ls/blob/main/docs/USAGE.md#neovim-v080) (or through mason.nvim + mason-lspconfig.nvim, which is what I had at first but neither method works now)
2. Observe error

![image](https://github.com/hashicorp/terraform-ls/assets/7560938/bbb7c493-bee2-40bd-9bf7-89085de3ce8e)

### Expected Behavior

Error should not occur, autocomplete should work.

### Actual Behavior

Error appears, autocomplete does not work. terraform-ls does still seem to be running in the background but it does nothing.

### Gist

https://gist.github.com/brw/b6efc9584f0d5725db00e55a6931a1e1

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by 9to6** [comment]
Hey guys. I found out the reason there are errors.
```
{"initializationOptions":[]
```

I think default value is not correct for `initialzationOptions`.
It is not map, is slice in golang syntax.

So, I added an option to avoid this exception, like below code block.
```lua
require("lspconfig").terraformls.setup({
    init_options = {
      terraform = {
        path = "/opt/homebrew/bin/terraform"
      }
    }
})
```

I hope it helps you guys.

**Comment by Allaman** [comment]
It is fixed in nvim-lspconfig (https://github.com/neovim/nvim-lspconfig/commit/75ab4fa8c16b64ec02581ce22879b52645e35def).
