### ISSUE TITLE
Workspace not initialized. Please run `terraform init`

### ISSUE THREAD

**Issue by MalikBagwala** [hashicorp/terraform-ls#166]
Terraform v0.12.24

Terraform VSCode extenstion 2.0.1

![image](https://user-images.githubusercontent.com/23068029/84755590-6e38b780-afdf-11ea-8653-4134e62c870b.png)

As you can see the terraform directory `aws` is not the root of the project ( The directory is initiated with appropriate workspace selected)

I am assuming the terraform extension looks for terraform files at the root of the project

Proposed Solution
Add a config file if possible(maybe `.terraform`) which may be a `yml` file denoting various configuration options.

eg. `directory: "./aws"`

**Comment by paultyng** [comment]
We are working to add multiple folder structure support currently, the best tracking issue is https://github.com/hashicorp/terraform-ls/issues/32#issuecomment-639543256
