### ISSUE TITLE
Enable CodeLens for type declarations

### ISSUE THREAD

**Issue by ricohomewood** [hashicorp/terraform-ls#169]
The previous versions of the extension had the ability to use CodeLens which showed where adn how many your declarations for Variables / Locals / Data etc where being consumed in you .tf files.

This gave you the insight where you have a decalred variable for example but is not being used, useful for large TF projects.

Please can we look to re-enable / integrate this very useful feature into the new extension?

**Comment by ricohomewood** [comment]
Any update on this?

**Comment by olegTarassov** [comment]
I believe this should be a must have vs enhancement. Coding in VSCode with hashicorp.terraform is brutal comparing to mauve.terraform. Most IDEs have referencing of resources, so not sure why this is not addressed given this was created last year 2020.

otherwise, thanks

**Comment by radeksimko** [comment]
This was implemented in https://github.com/hashicorp/terraform-ls/pull/584 which was shipped as part of `0.20.0`. Extension-side support was implemented in https://github.com/hashicorp/vscode-terraform/pull/686 which was also shipped as part of `2.14.0`.

Feel free to raise a new issue if you have any suggestions related to that feature (or any other feature) or if it doesn't work as you expect.

Thanks!
