### ISSUE TITLE
Offer Binaries with each release

### ISSUE THREAD

**Issue by klnusbaum** [hashicorp/terraform-ls#1816]
### Language Server Version

v0.34.2

### Problem Statement

Today, source code tars are made with each github release of terraform-ls. This means, to automatically install terraform-ls on a system I need to:
1. `curl` the source code tar
2. Extract it
3. Build the go code myself.

It would be really nice if, as part of the release process, pre-compiled binaries for various platforms were created. That way, users didn't need to do the compilation step.

Github has some ready-to-use workflows specifically for compiling binaries for Go applications that seem to make this process pretty easy. A good example of this is the [tf-migrate](https://github.com/minamijoyo/tfmigrate/blob/master/.github/workflows/release.yaml) release workflow.

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
Hi @klnusbaum, as described in https://github.com/hashicorp/terraform-ls/blob/main/docs/installation.md#installation, we provide pre-compiled binaries for most major platforms, and also produce packages for linux and macOS package managers.

Is there something we are missing there?

**Comment by klnusbaum** [comment]
I'm on Arch Linux which doesn't seem to be a supported distro :/

I figured, rather than going down the rabbit hole of supporting more Linux distros, it might just be easier to release the binaries.

**Comment by jpogran** [comment]
I understand Arch isn't on the list of published packages, but we do publish compiled binaries to https://releases.hashicorp.com/terraform-ls/. We publish 386, amd64, arm, and arm65 binaries compiled for linux, it's my understanding that these should work on Arch. These are built and signed by our build process, so you can verify it's from us.

I think that should take out your manual steps for building the binaries. We currently do not ship Arch packages, and I do not know when or if we will. I can pass that request onto our build team.

**Comment by klnusbaum** [comment]
Oh awesome! I didn't know these existed. These should work just fine. Thank you so much and sorry for the noise.
