### ISSUE TITLE
Not resolving variables of type object

### ISSUE THREAD

**Issue by windowsrefund** [hashicorp/terraform-ls#1819]
### Language Server Version

v0.34.2

### Terraform Version

v1.8.5

### Client Version

neovim 10.1

### Terraform Configuration

```terraform
In variables.tf

variable "foo" {
  type = object({
    bar = string
    baz = bool
  })
}
```

### Steps to Reproduce

Now in `main.tf` you should be able to autocomplete `var.foo.bar` or `var.foo.baz` but that doesn't happen.

### Expected Behavior

autocomplete should work

### Actual Behavior

autocomplete does not see anything deeper than `var.foo`

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
Hi @windowsrefund, this is something we are aware of: https://github.com/hashicorp/terraform-ls/issues/830 and https://github.com/hashicorp/terraform-ls/issues/653 come to mind. I do not have an ETA for you at this time.

**Comment by dbanck** [comment]
As James mentioned, I believe https://github.com/hashicorp/terraform-ls/issues/830 already covers this, so I'm going to close this as a duplicate to keep the conversation in one place.
