### ISSUE TITLE
cmd/version: Introduce JSON output

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#184]
### Current Version

```
0.3.2
```

### Use-cases

The VSCode extension and potentially other IDEs/extensions might want to manage the installation/upgrade of the language server. This would be little easier if they could read JSON output instead of line-based one.

### Attempted Solutions

https://github.com/hashicorp/vscode-terraform/blob/1c882b35bb52e834214fad186c167f8ecaf04804/src/languageServerInstaller.ts#L32-L33

### Proposal

Introduce `terraform-ls version -json` which has similar output to the recently introduced `terraform version -json`: https://github.com/hashicorp/terraform/pull/25252

**Comment by radeksimko** [comment]
@aeschright I'm aware we just keep updating without letting the user pin the LS to any version - so in the "happy path" this shouldn't cause problem once we upgrade most people to the version which has JSON output. But does the VSCode extension also check `--version` for custom installations?

**Comment by aeschright** [comment]
No, if you set an explicit path to the binary we don't do any further checks.
