### ISSUE TITLE
Goto definition breaks for object variables

### ISSUE THREAD

**Issue by mauriba** [hashicorp/terraform-ls#1866]
### Language Server Version

v0.35.0

### Terraform Version

Terraform v1.9.7 on windows_amd64

### Client Version

Neovim v0.10.2

### Terraform Configuration

```terraform
variable "linux_host" {
  type = object({
    name = string
  })
  default = {
    name = "linuxhost"
  }
}

locals {
  #vmname = var.linux_host          # Referencing the object itself instead of its fields does work
  #vmname = "vm-${var.linux_host}"  # Concatenating the variable disables goto-definition too!
  vmname = var.linux_host.name      # Doesn't recognize var.linux_host.name for goto-definition or lsp-hover
}
```

### Steps to Reproduce

1. Open Neovim (or probably any other editor) with terraformls configured
2. Create a new .tf file with the configuration specified above
3. Use your editor's csp client functions/keymaps to go to the definition or references of `var.linux_host.name`

### Expected Behavior

You should be redirected to the variable definition (goto definition) or the use of the variable in the local (goto references).

### Actual Behavior

Nothing. The lsp does not recognize the symbol.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Thanks for the report @mauriba!

I believe https://github.com/hashicorp/terraform-ls/issues/653 already covers this, so I'm going to close this as a duplicate to keep the conversation in one place.
