### ISSUE TITLE
No root module found for file.tf functionality may be limited

### ISSUE THREAD

**Issue by gelato** [hashicorp/terraform-ls#192]
### Server Version

```
0.4.0
```

### Terraform Version

```
Terraform v0.12.24
```

### Client Version

```
VSCcode Version: 1.46.1
```

### Terraform Configuration Files

```hcl
None
```

### Expected Behavior
No such message (No root module found for file.tf functionality may be limited) will appear

### Actual Behavior
Error message always popping out on file open operation.

### Steps to Reproduce
Get terraform code from git repo,  open file.

I don't run tf  code on my dev machine, and this Error message in  VSCode annoys me always when i open tf file.

**Comment by radeksimko** [comment]
Hi @gelato 
Terraform is a requirement for the Language Server and likely will be in the foreseeable future. This is what allows us to make it work across different versions of Terraform and different providers.

> I don't run tf code on my dev machine

Do you mind sharing some more details here? e.g. do you have Terraform installed at all? if not - why do you not wish to install it locally?

**Comment by gelato** [comment]
@radeksimko Good day, I do have terraform on my dev machine - i just don't run the code from this machine (i have dedicated deploy machine).
Here is what i do: i clone git repo, work on code and push my changes. Then on deploy machine i pull my changes and run terraform. I never did terraform init on my dev pc, because i don't need any unnecessary artifacts in the repo.

**Comment by radeksimko** [comment]
Understood.

The language server will not perform `plan`, `apply`, `destroy` or any similar operation.

With that in mind you should not need access to any particular providers (such as AWS, GCP, Azure etc.) from your dev machine as part of regular workflow. You _will_ however need to run `terraform init` in any root module(s) in your hierarchy as that downloads plugins which contain all that important metadata used in completion by the language server. `terraform init` alone should not require any special access other than access to the Terraform Registry (where it downloads providers from) and any module sources (Terraform Registry, GitHub, ...).

`init` is required (and will be in the foreseeable future) on any machine where you expect to use the language server as there is no other practical way of obtaining the provider metadata at this point.

Is there any reason you can't `init` root modules on your dev machine?

--- 

FYI If you use remote backend (and in most cases you should), you may still need to provide Terraform sufficient context (e.g. ENV variables) to authenticate against that backend for now. This is something we plan to address in the near future as per https://github.com/hashicorp/terraform-ls/issues/128 (which also contains some hints on how to provide that extra context) - ideally we'd like the process of obtaining schema to _not_ require state access in the long run.

**Comment by gelato** [comment]
@radeksimko I just don't want to store garbage files in my dev directory (which are not needed at development stage modules). Previous version of this plugin did not need terraform init process to run successfully... But  i  believe terraform-lsp was used there...

**Comment by paultyng** [comment]
@gelato I understand your concern here, and there are some possible ways we may be able to mitigate this a little down the road (see #193). 

That being said, using a built-in cache would tie you to a released versions of a provider/schema that were available at build time. There are currently 2,228 unique provider versions (meaning they have unique schema/completion data) that I see in the Provider registry right now. New versions are being shipped very often (AWS is weekly for example). If a version shipped after you installed your VS Code extension / LS, it would be out of sync with the completion data and cause issues in your editor.

Terraform 0.13 also allows users to publish their own providers in the registry, so the possible providers and versions of schema people use and want to be able to complete will just continue to grow and new providers may be introduced very frequently.

In addition to those complications, many users use custom or in-house providers, and we need the specific schema at the specific version they are using not just for completion data, but for diagnostics (ie. red squiggles), hover information, etc. 

The best solve for not requiring you to initialize on your local machine is probably the suggestion in #193, so probably best to just subscribe to that if its a feature you require for your workflow.
