### ISSUE TITLE
Search registry providers via completion

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#194]
### Use-cases

* Adding a provider to a workspace, need to search available providers that aren't present locally

### Proposal

Use a registry / algolia search endpoint to source possible providers based on a query.

**Comment by radeksimko** [comment]
This is now tracked under the following issues:

 - https://github.com/hashicorp/terraform-ls/issues/370
 - https://github.com/hashicorp/terraform-ls/issues/371
 - https://github.com/hashicorp/terraform-ls/issues/299
