### ISSUE TITLE
Add vscode option to suppress vscode toast notification for "No root module found, functionality may be limited"

### ISSUE THREAD

**Issue by sephross** [hashicorp/terraform-ls#207]
### Use-cases

Add option to suppress this vscode toast notification. Not all users are running terraform on their local machine, or may be in a repo containing many modules and initializing terraform in each one is not reasonable due to variable dependencies etc. In such scenarios this warning is endlessly distracting.

### Attempted Solutions

Running terraform init across many projects or modules in the same repo may not be manageable or reasonable.

### Proposal

Add option to suppress this warning, or reduce it to one time per module.

**Comment by radeksimko** [comment]
I think that reducing the message to once per module would make sense. 👍 

As mentioned in another thread though the warning has a reason. The language server won't do much without a root module. The only functionality available without schema is auto-formatting and most language features are likely going to require `init` because they need data from the providers, which are only available when `init`-ed.

On the positive note we do plan to investigate some ways of obtaining the schema from the registry, to provide a decent UX for those users who don't want to `init` or it's not practical for them to do it, see https://github.com/hashicorp/terraform-ls/issues/193

**Comment by sephross** [comment]
> The language server won't do much without a root module. The only functionality available without schema is auto-formatting

Definitely understand and appreciate this. For our own use, the text colour and formatter are the only things we've come to depend on with the vscode extension since the version 1 extension didn't have complete support for 0.12 from the beginning.

Another solution may be to simply separate out the non-LS functionality from the current vscode extension into its own vscode HCL formatting extension and subsequently avoid issues with LS detection all together.

**Comment by radeksimko** [comment]
That's useful context. Thank you.

I have done some refactoring in the related area (queued for the upcoming release) which made certain edge cases better exposed, so we can now think more clearly about how, when and whether to surface certain errors.

I described most of these in https://github.com/hashicorp/terraform-ls/issues/218

I'm still not fully convinced I would want the server to entirely ignore all the conditions described there, but I do understand that the current way of surfacing it is too simple/naive. I would therefore appreciate your feedback there.

**Comment by dmikalova** [comment]
Please let us just turn off the notifications, or put documentation on the plugin page and the readmes at the root of the repo on what needs to be done to correctly configure that.

**Comment by woz5999** [comment]
i agree with @dmikalova @sephross 

i care much more about not getting constantly nagged than i am about having access to all the LS features. just let me turn these notifications off.

**Comment by i255d** [comment]
So, how do we turn it off in VSCode?

**Comment by ayk33** [comment]
Is there a way to disable the notifications? They get pretty spammy..

**Comment by radeksimko** [comment]
Hi folks,
The issue is not addressed _yet_, but we have a plan for addressing it and I'm just merging all the issues with the same root cause, such as this one, into a single issue: https://github.com/hashicorp/terraform-ls/issues/424

Thank you for your understanding and patience.
