### ISSUE TITLE
High CPU utilisation

### ISSUE THREAD

**Issue by m1keil** [hashicorp/terraform-ls#230]
Hello,

Running latest VSCode and Terraform v2.0.2 extension.
From time to time I find `terraform-ls` pegging single core for 100% utilization for long periods of time. I usually have to kill it:

![image](https://user-images.githubusercontent.com/1589008/87222029-c8952000-c3b3-11ea-9d37-626fd7475d5c.png)

Not exactly sure what's going on. I think currently our project structure is not compatible with the assumptions of the extension as we use a sort of monorepo where terraform is just one part of. So the extension doesn't really work for us at the moment, but I don't know why the language server is stuck such high utilization like that.

**Comment by radeksimko** [comment]
@m1keil Thank you for the report. There were some recent changes released on Friday (`v0.5.1`) in how we discover and load root modules and some other people have reported they don't experience high CPU anymore, when they did. Are you on this latest version?

Either way I would like to take this conversation to #217 just to keep it in once place, so I'm going to close this issue, but please do let us know if you are still experiencing this problem after upgrading (in #217 ).

**Comment by m1keil** [comment]
Thank you. Sorry haven't found that issue when searching. I will check the new version and report if I hit any cpu issues.
