### ISSUE TITLE
Expose Terraform-related options via native LSP "InitializationOptions"

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#240]
### Current Version

```
0.5.3
```

### Use-cases

Currently we only expose `rootModulePaths` in "LSP native" configuration:

https://github.com/hashicorp/terraform-ls/blob/a1ff20f9f5378eaf2b224f84c8bc05b2028da18f/internal/settings/settings.go#L11-L13

Some runtime settings which we don't strictly need to know before the server is actually initialized is still exposed via CLI flags only, e.g. all Terraform-related options:

https://github.com/hashicorp/terraform-ls/blob/a1ff20f9f5378eaf2b224f84c8bc05b2028da18f/commands/serve_command.go#L43-L47 

We execute Terraform _after_ the initialization, so these settings would be better suited for the LSP native configuration, which in the long run could also be modified at runtime via [`workspace/didChangeConfiguration`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeConfiguration).

### Attempted Solutions

Keep using flags

### Proposal

We can expose the configuration as `terraformExecPath`, `terraformExecTimeout` and `terraformLogPath`.

https://github.com/hashicorp/terraform-ls/blob/a1ff20f9f5378eaf2b224f84c8bc05b2028da18f/internal/settings/settings.go#L15-L18

I wouldn't go as far as removing the existing flags in favour of LSP settings _yet_, but I _would_ document that as the preferred way of configuring these options and I would only allow one of these ways of configuring any option at a time. i.e. I would error out the initialization if the same settings is provided via flag _and_ LSP.

**Comment by danishprakash** [comment]
@radeksimko is this open for external first time contributors to this project? I'd like to work on this.

**Comment by radeksimko** [comment]
Hi @danishprakash 
Yes, this one is a good issue for any first time contributor. Feel free to ask questions and/or raise a PR.

**Comment by radeksimko** [comment]
The only thing I would not here though after re-reading my original issue is that `tfExecLogPath` is probably not suitable for exposing via LSP as we need logging _before_ any LSP request is received, so I would only focus on the other two options.

**Comment by danishprakash** [comment]
@radeksimko thanks for the info. I've implemented the changes for `TerraformExecPath` [here](https://github.com/hashicorp/terraform-ls/compare/main...danishprakash:danish-init-opts?expand=1). If that approach looks good, I can add `TerraformExecTimeout` and then raise a PR. Thanks.

PS. the relevant client changes required to test these changes end to end are [here](https://github.com/hashicorp/vscode-terraform/compare/main...danishprakash:danish-init-opts?expand=1).

**Comment by radeksimko** [comment]
It looks reasonable at first sight. We usually prefer to just raise the PR straight away as we can discuss on the relevant LOC there instead of abstractly pointing to it from here.

**Comment by radeksimko** [comment]
Reopening until remaining 2 options are added.

**Comment by radeksimko** [comment]
And I take back what I said about `tfExecLogPath` - we shouldn't need to run Terraform before `initialize` request and the recent refactoring done in #588 confirms this, so both options should now be eligible for exposure via LSP.

**Comment by danishprakash** [comment]
> Reopening until remaining 2 options are added.
Sure, will look into those. Thanks for the help!
