### ISSUE TITLE
Reference count and go to definition

### ISSUE THREAD

**Issue by Chupaka** [hashicorp/terraform-ls#254]
In v1.4.0 (TF 0.11) I see reference count for objects and can Cmd+click any interpolation to go to object definition.

<img width="405" alt="Screen Shot 2020-08-04 at 19 36 31" src="https://user-images.githubusercontent.com/3432808/89320387-18e96000-d68a-11ea-9271-cb49eb5b7697.png">

After upgrade to the latest version, I can't see any of it anymore:
<img width="491" alt="Screen Shot 2020-08-05 at 10 48 38" src="https://user-images.githubusercontent.com/3432808/89386155-59d48980-d709-11ea-99c2-a19e47ae4a8a.png">

Are there some settings to bring it back?

**Comment by radeksimko** [comment]
Just to set the expectations right though - it's unlikely we will bring back this functionality for 0.11 or any older Terraform versions, or if we do it would be very limited. This is due to the fact that 0.11 requires entirely different parser since it uses HCL1.

**Comment by Chupaka** [comment]
That's okay, we started the process of migration from 0.11 to 0.12 and are looking for the same UX as we had with 0.11.

**Comment by H2so4** [comment]
+1 on this feature please

**Comment by sata** [comment]
Hi maintainers, thanks for this language server implementation. Are there any plans on extending the feature set anytime soon to cover go to definition and find usage similar to the plugin for Intellij? 

It would be amazing to have it as a lot more editors would be able to leverage same feature set :)

**Comment by radeksimko** [comment]
Hi folks,
the following two features were shipped today in 0.19.0:

 - go-to-definition (go to attribute or block from address) #569
 - go-to-references (go to addresses from a block or an attribute) #572, #580

I am currently trying to implement the reference count as a code lens and aiming for it to be part of the next release.

Thanks for your patience.

**Comment by Chupaka** [comment]
@radeksimko Yeah, thanks, checking it right now. However, can't get "Go to References" work. Can it be it works only inside a single file?

E.g. I successfully go to a variable definition in a separate file, but clicking "Go to References" on it says "No references found"

**Comment by radeksimko** [comment]
@Chupaka Navigating across files should work in both cases. Can you file a new issue for this one and attach the relevant config(s), please?

**Comment by radeksimko** [comment]
This was implemented as part of https://github.com/hashicorp/vscode-terraform/pull/686 which was shipped in extension version `2.14.0` and https://github.com/hashicorp/terraform-ls/pull/584 which was shipped in language server version `0.20.0` (yesterday's release).

There are further planned improvements in this area - feel free to subscribe to any of these issues

 - https://github.com/hashicorp/vscode-terraform/issues/706
 - https://github.com/hashicorp/vscode-terraform/issues/670
 - https://github.com/hashicorp/terraform-ls/issues/558 / https://github.com/hashicorp/vscode-terraform/issues/669
 - https://github.com/hashicorp/terraform-ls/issues/581
 - https://github.com/hashicorp/terraform-ls/issues/583

or open a new one if the problem/feature isn't described in any of them.
