### ISSUE TITLE
Validate configuration and publish diagnostics

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#27]
Currently the language server ignores any potential errors or warnings.

In order for completion (and other future features) to work this is essential as we need to expect user will want to use LS features in incomplete and otherwise invalid configs and HCL has the ability to deal with such scenarios.

That said the user would benefit from having a feedback in the form of errors/warnings when their config is not up to scratch.

As part of this we need to assess **what** diagnostics and **when** to publish.

## What

 - HCL parse errors
 - provider validation
 - anything else that `terraform validate` may run - perhaps consider even running _that_ directly

### `terraform validate`

`terraform validate` can parse config and provide this data in JSON readable format (via `-json` flag).
The only caveat is that it also reports what could be interpreted as false negatives in the context of the language server.

This is because the command was originally designed to test preparedness for `plan`/`apply` and as such it will also report missing required variables that could be provided as ENV variables in CI or elsewhere - generally somewhere outside the context of an editor and language server.

For these reasons we may need to suppress such errors, or just find a different way of validating configs.

Relatedly integrating `validate` at this point would be setting a new precedent of Terraform actually parsing the config and Terraform's parsing logic _may_ differ (hopefully doesn't though) from how the language server one. It is therefore important to integrate validation with this in mind.

## When

 - on `textDocument/didChange`
   - this could be potentially resource-intensive depending on how often do Language Clients send changes. Reparsing configuration on every keystroke may not be a good idea.
   - may not provide the best UX as the user is in the process of crafting a valid config and so they are likely to be aware that it's not valid _yet_.
 - on `textDocument/didSave`, `textDocument/willSave` or `textDocument/willSaveWaitUntil`
   - this could leave the user potentially puzzled while looking at invalid config wondering why it is invalid

Generally for _when_ I think that some user testing/surveying should happen so we know when users expect their configs to be valid and when do they expect to receive feedback if it is not valid.

**Comment by apparentlymart** [comment]
I don't know that it really changes anything about what you described here, but I just wanted to note that `terraform validate` _is_ intended for use-cases like this (albeit more like "validate on save" than ongoing checking with language server, because there was no such thing as a language server when we designed it that way) and we consider the errors that appear for provider configurations to be a bug, tracked by hashicorp/terraform#21408.

I don't know if it would help given the rest of the constraints here, but I'd be open to considering fixing that bug to be part of the solution to this issue, if that's helpful.
