### ISSUE TITLE
TF_PLUGIN_CACHE_DIR not respected

### ISSUE THREAD

**Issue by cyrus-mc** [hashicorp/terraform-ls#291]
### Server Version
```
terraform-ls --version
0.9.0
```

### Terraform Version

```
terraform version
Terraform v0.12.29
+ provider.aws v2.70.0
+ provider.external v2.0.0
+ provider.null v3.0.0
+ provider.template v2.2.0
+ provider.vault v2.15.0
```

### Client Version

```
VsCode v2.2.3
```

### Terraform Configuration Files

```hcl
N/A
```

### Expected Behavior
Env var TF_PLUGIN_CACHE_DIR is set under which plugins are downloaded. Auto-completion should work as if the plugins where downloaded within the cwd directory at ~/.terraform/plugins.

### Actual Behavior
Autocompletion does not work. 

### Steps to Reproduce

1. set and export env var TF_PLUGIN_CACHE_DIR
2. Open some Terraform code (ie: /home/user/main.tf)
3. Check if auto-completion for AWS resources (as an example) works
4. If you under TF_PLUGIN_CACHE_DIR and re-run terraform init plugins are downloaded in the cwd under .terraform and then auto-completion works.

**Comment by radeksimko** [comment]
Hi @cyrus-mc 
You are right that this is not supported yet. We have that issue tracked under https://github.com/hashicorp/terraform-ls/issues/24 already, so I'm going to close this one to consolidate. Feel free to subscribe to #24
