### ISSUE TITLE
Autocomplete not working in new files

### ISSUE THREAD

**Issue by IanMoroney** [hashicorp/terraform-ls#295]
Unable to use language server features inside new files, as autocomplete gets it wrong every time.

Start typing "r" to get resource, and it inserts "rresource" instead of autocompleting the word...

![rresource](https://user-images.githubusercontent.com/10791260/98933572-bb5e7e00-24d8-11eb-85e8-0a2b3a74e024.gif)

**Comment by radeksimko** [comment]
Reproduced, thank you for the report. I'll look into this!

**Comment by radeksimko** [comment]
This is fixed in #298 which will be part of the upcoming 0.10.0 release.

Thank you again for reporting this bug.
