### ISSUE TITLE
Include "Verified" provider schemas in the LS builds.

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#321]
We should expand preloaded schemas from #302 to include both "Official" and "Verified" assuming the resulting binary is not prohibitively large and performance is not adversely affected.

**Comment by radeksimko** [comment]
We discussed this before, but I'll just note it here for posterity:

In addition to the binary size, the codebase size is also a concern, so as part of this work we should consider generating schemas as part of the release. Sadly this will make builds practically unreproducible, but I think it's ok trade-off for the value added and considering this is mostly a temporary solution until https://github.com/hashicorp/terraform-ls/issues/193 is resolved.
