### ISSUE TITLE
Crash on hovering identifier

### ISSUE THREAD

**Issue by rchl** [hashicorp/terraform-ls#328]
### Server Version

```
0.10.0
```

### Terraform Version

```
Terraform v0.14.0
```

### Client Version

```
Sublime Text LSP v1.2.1
```

### Terraform Configuration Files

This is a part of the file. Not sure if it will reproduce in isolation:

```hcl
locals {
  identifiers_pull_stage = var.allow_stage ? [format(
    "arn:aws:iam::%d:role/stage_v2_%s_exec",
    module.global.account_numbers["stage"],
    local.app_id
  )] : []

  identifiers_pull_prod = var.allow_prod ? [format(
    "arn:aws:iam::%d:role/prod_v2_%s_exec",
    module.global.account_numbers["prod"],
    local.app_id
  )] : []

  identifiers_pull = compact(concat(
    local.identifiers_pull_stage,
    local.identifiers_pull_prod,
    var.ecr_identifiers_pull
  ))
}
```

### Log Output

https://gist.github.com/rchl/d48fd8319313e13498140c81d3ca9757

### Expected Behavior

No crash

### Actual Behavior

Crashes

### Steps to Reproduce

Hover the `var.ecr_identifiers_pull` part.

**Comment by radeksimko** [comment]
I believe this was fixed in https://github.com/hashicorp/terraform-ls/pull/320 which was not released yet, but will be very soon.
