### ISSUE TITLE
ARM64 support/package creation

### ISSUE THREAD

**Issue by lcworld** [hashicorp/terraform-ls#342]
### Use-cases
Please support ARM64 so we could use this tool in extension "HashiCorp Terraform" for Visual Studio Code on Raspberry Pi with 64 bits OS (Ubuntu or Raspberry OS)

### Attempted Solutions
I tried to build the tool on Ubuntu 20.04.1 arm64, on Raspberry pi 4 / 8 GB.
I run make command after cloning git repository.

```
2020/12/27 22:39:24 root_module.go:613: parsing file "main.tf"
--- PASS: TestSchemaForPath_uninitialized (5.90s)
PASS
coverage: 57.0% of statements
ok      github.com/hashicorp/terraform-ls/internal/terraform/rootmodule 6.870s  coverage: 57.0% of statements
=== RUN   TestURIFromPath
--- PASS: TestURIFromPath (0.00s)
PASS
coverage: 100.0% of statements
ok      github.com/hashicorp/terraform-ls/internal/uri  0.032s  coverage: 100.0% of statements
?       github.com/hashicorp/terraform-ls/internal/watcher    [no test files]
FAIL
make: *** [Makefile:7: test] Error 1
```

I decided to execute "go build" command, and the binary terraform-ls was created correctly.
I'm going to test it later.

**Comment by lcworld** [comment]
commit id  efacdb82dcc1fe0d61dba1935163ef4da795473a

**Comment by radeksimko** [comment]
We certainly plan to release darwin/arm64 binaries, but this will most likely depend on Go 1.16 release (currently planned for Feb 2020) and this goreleaser change https://github.com/goreleaser/goreleaser/pull/1956

I am aware there is 1.16 beta release out, but I'm unsure of the implications, esp. wrt availability in GitHub Actions and potential of breaking changes. Finally we don't have a good way of cutting just one release for darwin/arm64 on a later version of Go than the rest of releases - and we do not intend to use beta release of Go for any other releases.

**Comment by radeksimko** [comment]
Apparently I completely misread this issue! Now I see it's about `linux/arm64`, not Apple Silicon. That I think we can support probably straight away - I will look into it.

**Comment by radeksimko** [comment]
This is a dedicated issue for `darwin/arm64` just in case anyone lands here looking for it: https://github.com/hashicorp/terraform-ls/issues/349

**Comment by radeksimko** [comment]
PR pending review: #351 

Just FYI Terraform (core) only started releasing `linux/arm64` packages since 0.13.5, so you would need to have that version of Terraform to take advantage of such LS build.

Also providers are released independently of Terraform and LS so you might need to ask maintainers in relevant repositories on individual basis to make similar changes if `terraform init` fails for a provider.
