### ISSUE TITLE
textDocument/complete: Complete references to named values

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#38]
## Context

Currently the LS completes block's known attributes and nested blocks per schema and naively assumes values are static.

Terraform language supports [references to named values](https://www.terraform.io/docs/configuration/expressions.html#references-to-named-values) which are generally formatted as dot-based addresses, e.g.

```hcl
variable "example" {
  default = "example-value"
}
data "aws_availability_zones" "names" {
}
```
can be referenced as `var.example` or `data.aws_availability_zones.names` respectively elsewhere in the configuration.

## Requirements

Completing the references requires LS understanding a couple of things it _doesn't_ understand today:

 - relationship between address format and block type
   - e.g. knowing that `var.<name>` belongs to `variable` block and evaluates to variable's _value_ (which may come from its `default`)
 - context in which references are evaluated, for example
   - `local` values can be referenced between each other, but `variable`s can not
   - `backend` blocks do not support any kind of interpolation
   - `provider` blocks have limited interpolation capabilities (e.g. via `alias`)
   - values have types and it would be suboptimal to suggest references that do not match the destination type (e.g. `var.number` for a string attribute)
 - whether the value is available locally within the configuration or from the state, e.g.
   - variable values would generally be local
   - data source and resource attributes would generally come from state, unless these attributes are referencing static values (such as variables)

## How could we tackle this

This will likely require extensive design work to ensure stability and maintainability over time. There is a number of factors to consider, e.g.

 - How does #36 overlap with this problem
 - How will the functionality overlap with https://github.com/hashicorp/terraform/tree/master/addrs
   - we probably won't build a separate single library which decouples this logic yet, but should keep this option in mind as the risk of drifting from Terraform is real
 - We may need to keep (re-)parsing the whole workspace as opposed to just open files and hold the AST for the whole workspace in memory, as references are workspace-wide, not file-wide
   - we should resolve #15 first

For reasons above I would encourage discussing the design of the possible solution(s) here before attempting to raise a PR.

**Comment by Liquidmantis** [comment]
Since this is the issue being referenced in the issues on autocomplete, I just wanted to say that All Autocomplete has been a good workaround for me in the interim.  You have to load your project files so that it's aware of variables. 

https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete

**Comment by radeksimko** [comment]
Initial support for references was added in (now merged) https://github.com/hashicorp/terraform-ls/pull/485 which will be released in coming days. The same PR also includes some description of features added and links to follow-up issues covering features which were omitted from that initial PR.

With that in mind I'm going to close this issue but keep an eye out for the upcoming update (0.17.0).
