### ISSUE TITLE
Remove notification boxes

### ISSUE THREAD

**Issue by oliversalzburg** [hashicorp/terraform-ls#383]
### Current Version

```
0.12.1
```

### Use-cases

When editing modules in VS Code to which terraform-ls can not determine the root module, it will directly call into VS Code API to open GUI notifications. The LS will keep popping up the notification consistently for every single time the active document is changed.

Editing standalone modules can not be so rare of a use case that it requires this level of interference.

### Attempted Solutions

The calls are hardcoded at https://github.com/hashicorp/terraform-ls/blob/main/internal/langserver/handlers/did_open.go#L138 and https://github.com/hashicorp/terraform-ls/blob/main/internal/langserver/handlers/did_open.go#L93 and can not be disabled by themselves.

### Proposal

The LS should not invoke APIs that directly interfer with the UI. There is an existing output channel to communicate any issues and if user interaction is required, it should be proxied through the main IDE extension.

The IDE extension is presumeably far better equipped to handle these notifiations in a non-distracting way (like a status bar indication).

**Comment by radeksimko** [comment]
Hi,
The issue is not addressed yet, but we have a plan for addressing it and I'm just merging all the issues with the same root cause, such as this one, into a single issue: #424

Thank you for your understanding and patience.
