### ISSUE TITLE
Incorrect semantic highlighting for block braces

### ISSUE THREAD

**Issue by pjmiravalle** [hashicorp/terraform-ls#387]
When `editor.semanticHighlighting.enabled` is set to `true` in vscode, it causes an issue with syntax highlighting for resource/data block declarations.

Specifically, the curly brace bracket(s) after `resource "type" "name"` is wrapped *in the same* syntax highlighting token that is used for `"type" "name"`, which causes the bracket to take on the wrong color in the editor. Hopefully that makes sense.

My guess is that the recent additions of this extension dipping its toes into using semantic tokens (#523) is causing this to occur.

### `editor.semanticHighlighting.enabled` ENABLED
![Screen Shot 2021-02-02 at 11 23 33 AM](https://user-images.githubusercontent.com/4603979/106639035-248ae600-654a-11eb-87d7-a7dc8688a12e.png)

This also seems to happen for data resource declarations:
![Screen Shot 2021-02-02 at 11 22 07 AM](https://user-images.githubusercontent.com/4603979/106639141-46846880-654a-11eb-8c7a-faf9dbb645bb.png)

### `editor.semanticHighlighting.enabled` DISABLED
![Screen Shot 2021-02-02 at 11 24 36 AM](https://user-images.githubusercontent.com/4603979/106638995-1a68e780-654a-11eb-8dc5-80e30123f8af.png)

**Comment by radeksimko** [comment]
I just raised a PR with fix https://github.com/hashicorp/terraform-ls/pull/390, which once reviewed and merged will be part of the next LS release. VS Code in particular should then download and install the new version of LS automatically on launch and fix the problem there.
