### ISSUE TITLE
Click-to-documentation on terraform registry

### ISSUE THREAD

**Issue by nfx** [hashicorp/terraform-ls#409]
I'm working with tf files a lot and i'd like to click-to-open-in-browser on resource names and resource properties. Terraform registry is having all standard URL format for resource names and property names (just `#property_name` anchors) and it should probably be not that hard to implement it. Would save tons of people tons of time.

**Comment by radeksimko** [comment]
Hi folks,
I have just released language server 0.14.0 which introduces initial support for docs links to providers as per #402 

We don't have predictable deeplinks for resource or data source docs pages yet, but this feature is tracked under https://github.com/hashicorp/terraform-ls/issues/190

With that in mind I'm going to close this issue.

The new release of LS should be automatically available on the next launch of your VS Code, assuming you use our official Terraform extension.

**Comment by nfx** [comment]
@radeksimko - but can we have this on the editor level?.. as "lens"?
