### ISSUE TITLE
Provide way of highlighting/formatting Nomad configuration files

### ISSUE THREAD

**Issue by mxab** [hashicorp/terraform-ls#410]
### Current Version

```
0.13.0
```

### Use-cases

We use terraform to render templated nomad files. E.g.:

```hcl
job "foo" {
 ...
 env {
  FOO = "${foo}"
 }
}
```
```hcl
resource "nomad_job" "my_job" {
  jobspec = templatefile("${path.module}/job.tmpl.hcl", {
    foo = "bar"
  })
}
```

Since one of the latest releases, vscode formats

`FOO = "${foo}"` to `FOO = foo` and therefore breaking the template.

### Proposal

Allow to disable this kind of formating feature in some settings for certain files e.g.: `*.tmpl.hcl`

**Comment by radeksimko** [comment]
Hi @mxab 
Do you mind sharing some more details about your setup? Specifically what client/editor/extension and version of client/editor/extension do you use with the language server?

As far as I'm aware most clients do claim `*.hcl` for the purposes of syntax highlighting, but should never be sending `*.hcl` files to the _Terraform_ language server, so if this is happening, we should report it to the relevant client and get it fixed there.

The client is always responsible for detecting syntax (based on file extensions or anything else) and for sending the right files to the server. The server itself in theory could refuse to process such files, but there are no documented ways to do this and more importantly this would just violate the [LSP](https://microsoft.github.io/language-server-protocol/).

**Comment by mxab** [comment]
Hi,
ok in my case I was setting the hcl file in the vscode to `terraform` language mode. I was doing this because I wanted to benefit from the formatting of my templated nomad file which ends with `.hcl`

So as I understand this now, this is not a supported use case? Any ideas how to format such a file?
Terraform Extension `v2.7.0`

**Comment by radeksimko** [comment]
> So as I understand this now, this is not a supported use case?

Correct, the Terraform language server does _not_ and in foreseeable future will not support non-Terraform files. The only other format it will likely ever support is `*.tfvars` files and potentially the new `.terraform.lock.hcl` file.

> Any ideas how to format such a file?

For **syntax highlighting** you could try this community maintained VS Code extension: https://marketplace.visualstudio.com/items?itemName=wholroyd.HCL However be aware that it also claims `*.tf` files and we have seen in practice this conflict sadly isn't handled well by VS Code itself and may cause the Terraform extension (which also claims `*.tf`) to freeze.

We have some future plans for generalizing [the existing TextMate grammar](https://github.com/hashicorp/vscode-terraform/blob/main/syntaxes/terraform.tmGrammar.json) used by the VS Code extension, which is currently Terraform specific anyway (it _might_ work for highlighting other HCL languages but it was not designed for that).

I assume that once we publish such a generic HCL grammar it can be used for highlighting Nomad job spec files in some shape or form, at least until/unless we publish a Nomad extension which would offer better and more accurate highlighting based on Nomad-specific schema.

For other language features (such as **formatting**) I am aware there is a [Nomad language server](https://github.com/juliosueiras/nomad-lsp), but I haven't seen any corresponding clients/extensions anywhere.

**Comment by mxab** [comment]
Ok, thanks for letting me know.

For highlighting I use already the mentioned hcl extension in some use cases

But formatting was more the issue, which worked ok until one of the last releases, but I assume this is not something you going to revert :)

I guess I need to find a different way to keep the files formated.

You can close this issue I guess
