### ISSUE TITLE
Allow disabling of cmd + hover opening docs

### ISSUE THREAD

**Issue by shelmire** [hashicorp/terraform-ls#415]
Hi there,

I'm not really sure the right place for this, or even if it's caused by the language server, though I think it is. Whenever I cmd + hover over something (like aws_subnet), a browser tab opens to that page in the docs.

I find the constant opening of new tabs extremely annoying. It triggers, for example, when doing a copy/paste (for example, selecting a string like aws_vpc.main.id). Before hitting the command button for any reason, I have to be quite sure that my mouse is not hovering over a word that exists in the terraform docs.

I uninstalled the Terraform extension and restarted vs code, yet this behavior persisted. I tried reinstalling the vs code extension and disabling the language server via the command pallet; yet this behavior persists.

Any insight into this problem or ability to disable the language server (which does not seem to work from the accompanying extension, and seems to exist independently of it) would be great. I have not installed it outside of vs code, terraform-ls returns command not found.

Thanks!

**Comment by radeksimko** [comment]
Hi @shelmire 
The support for links was merged very recently, but not actually released yet - it will be released hopefully today once we iron out some last minute CI issues.

This makes me wonder if maybe you are using a different VS Code extension, or older version of it, which is pulling the links from somewhere? Can you double check the list of all your installed extensions in VS Code and ensure that the HashiCorp one is the only one catching `*.tf` files?

**Comment by radeksimko** [comment]
To your UX question though - this will be rolled out initially just for provider block labels, so resources or data sources won't have links yet anyway.

See screenshots at https://github.com/hashicorp/terraform-ls/pull/402

Additionally we will be tracking visits from both hover links and these `Ctrl+click` links (which each come from a different underlying LSP method) and equally collecting user feedback such as this one once it is released. Based on the data and feedback we can still change how we expose the links.

**Comment by shelmire** [comment]
@radeksimko thanks for your patience. You are correct, the problem was caused by erd0s.terraform-autocomplete. This seems to be some undocumented behavior or misbehavior of the Go To Definition for that extension. Sorry to bother you, thanks again for your work!

I think displaying the links on hover is great so long as they don't open new browser tabs! :-)
