### ISSUE TITLE
References don't track when using compound strings with variables

### ISSUE THREAD

**Issue by tcreatorxxx** [hashicorp/terraform-ls#422]
Example code:
`name = "${var.one}-${var.two}-${var.three}"`

In `variables` block you will see `0 references` above each of `one`, `two` or `three` variable.

Version of VS Code: 1.29.0
Version of plugin: 1.3.7

**Comment by radeksimko** [comment]
Hi folks,
code lenses / reference counting is not yet implemented on the language server side (where I just transferred this issue), but it is more generally tracked under https://github.com/hashicorp/terraform-ls/issues/169

I'm going to close this issue to keep the discussion about that feature in one place and I assume that once we do support it, it will not have this bug that was present in client-side implementation of the VS Code v1 extension.

Thank you for understanding and patience.
