### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BAAdeosun** [hashicorp/terraform-ls#433]
- Issue Type: `Performance`
- Extension Name: `terraform`
- Extension Version: `2.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\xxxxxx\AppData\Local\Temp\hashicorp.terraform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by radeksimko** [comment]
Hi @BAAdeosun 
I'm afraid we would need more data to be able to investigate a problem of this nature.

I did fix a problem that would in the past cause CPU spikes in the language server: https://github.com/hashicorp/terraform-ls/pull/391 (released in 0.13.0 of terraform-ls).

You can try restarting VS Code and that should prompt upgrade to the latest language server version, if you happen to be still running a version older than `0.13.0`.

Given the lack of cpuprofile.txt, I am not able to investigate any further, so I'm going to close this issue, but feel free to comment or open a new one with that file and provide more details.
