### ISSUE TITLE
build: Add MacOS notarization

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#44]
As noted in https://github.com/hashicorp/terraform-ls/pull/43 MacOS/darwin builds are prevented from being launched on MacOS Catalina because they are not signed.

We should look into signing - it seems to be supported in goreleaser:
https://goreleaser.com/customization/#signing-with-gon

**Comment by mitchellh** [comment]
Its a bit weird but you can look at Gon's `.goreleaser.yml` as an example. Its a strange one cause I only have to build for Darwin (since notarization only works there): https://github.com/mitchellh/gon/blob/master/.goreleaser.yml

**Comment by radeksimko** [comment]
@mitchellh Thanks Mitchell, I am aware of Gon's integration with GoReleaser, but I want to leverage our signing workflow we already have in place for our other tools, just so that everything is signed the same way (e.g. bundle IDs and binary names follow the same pattern) and we are not spreading our Apple Dev credentials across multiple projects, as that makes rotation more difficult.

Whether I use the native integration or not though, the signing interface seems somewhat suboptimal as I explained in https://github.com/goreleaser/goreleaser/issues/1411

I suspect this is also why gon is distributed as two packages - [unsigned ZIP and signed DMG](https://github.com/mitchellh/gon/releases)?

Either way the above is what led me into raising https://github.com/goreleaser/goreleaser/pull/1414 and the next step for me now is to leverage these new hooks and try signing that way.
