### ISSUE TITLE
Missing apt repository target for Ubuntu "Hirsute Hippo" (21.04)

### ISSUE THREAD

**Issue by moritzheiber** [hashicorp/terraform-ls#470]
It would appear the Debian/Ubuntu Hashicorp `apt` repository at `apt.releases.hashicorp.com` is missing a target for `terraform-ls` for the latest Ubuntu release, "Hirsute Hippo" (21.04):

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
$ apt policy terraform-ls
N: Unable to locate package terraform-ls
```
The repository is valid and carries packages for other Hashicorp products:
```console
$ apt policy vault
vault:
  Installed: 1.7.1
  Candidate: 1.7.1
  Version table:
 *** 1.7.1 500
        500 https://apt.releases.hashicorp.com hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
# [...]
```
It does have a proper target for e.g. "Focal Fossa" (20.04 LTS):
```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
$ apt policy terraform-ls
terraform-ls:
  Installed: (none)
  Candidate: 0.15.0
  Version table:
     0.15.0 500
        500 https://apt.releases.hashicorp.com focal/main amd64 Packages
```

### Expected Behavior
I would like to be able to install `terraform-ls` using the `apt` repository provided by Hashicorp.

### Actual Behavior
I'm unable to install `terraform-ls` from the `apt` repository because there doesn't appear to be a package available for the Ubuntu distribution version I'm running:

```console
$ sudo apt install terraform-ls
# [...]
E: Unable to locate package terraform-ls
```

### Steps to Reproduce
1. Use a running "Hirsute Hippo" Ubuntu installation or container
2. Add the `apt` repository as described in the documentation
3. Run `sudo apt install terraform-ls`
4. Observe failure to install because of missing package

**Comment by radeksimko** [comment]
Thank you for the report Moritz,
I was able to reproduce this and raised it with our release engineering team who are responsible for packaging all these Linux packages.

**Comment by moritzheiber** [comment]
@radeksimko Thanks Radek, appreciate it!

**Comment by radeksimko** [comment]
FYI: My colleague saw that _new_ releases are in fact making their way to that repo for `Hirsute Hippo`, so you should now see yesterday's 0.16.0 release there. However he's still looking into why packages for old releases weren't created.

**Comment by moritzheiber** [comment]
@radeksimko I can confirm that the new release is available from the repository!
