### ISSUE TITLE
High memory usage with multiple folders

### ISSUE THREAD

**Issue by rich-cumbers** [hashicorp/terraform-ls#484]
I am seeing very high amounts of memory usage from my Visual Studio Code, that seem to be linked to the Terraform language server.

I have a workspace, with 7 folders - all are terraform modules. With the language server off, memory usage is around 325MB for my WSL2 Ubuntu virtual machine. Turning on the language server, that ramps up to 1.8GB, and if I add more terraform folders, the memory consumption keeps increasing.  Turning off the language server results in the memory being reduced again to pre-language server levels

Previously I had a workspace with 20-25 terraform folders, but that is now unusable with the Terraform Language Server. I don't know if this is related to recent releases of the extension, but it does feel like I would have noticed before the latest updates

Am I holding the extension wrong (using vanilla settings), or is there something wrong with the latest extension version?

**Comment by radeksimko** [comment]
Hi @rich-cumbers 
we haven't done any particular memory usage optimizations, but 1.8GB for a single LS instance looks quite high.

I would expect the memory usage per instance to be affected by the following

 - amount of providers used (and size of these providers when it comes to schema)
 - amount of modules declared
 - overall amount of Terraform configuration

I'm sure there are places where we could trade some CPU for memory and vice versa, but this has not been a priority so far.

It is also worth mentioning that the language server currently doesn't support multiple folders/workspaces natively yet, so clients (such as the Terraform VS Code extension) typically launch 1 instance of LS per workspace. See https://github.com/hashicorp/terraform-ls/issues/482

With all that in mind - can you check how many instances of `terraform-ls` are running and how much memory does _each_ typically consume? Then for any instance/workspace that seems too high - can you give me some details based on the above (providers used, no. of modules, LOC of configuration)?

I have a single instance running currently with `hashicorp/aws` and `hashicorp/random`, just a single module and single file, which consumes about 200MB - which admittedly is not ideal, but to be fair we retain whole schema of the AWS provider in memory and it is one of the biggest providers in the number of resources and data sources, so I would guess that may be a factor.

**Comment by rich-cumbers** [comment]
Hi @radeksimko ,

Thanks for the speedy response! Points as follows:

- The 7 folders that i have are each their own 'module', 
- Each folder in VSCode spins up a terraform-ls process as you mention
- All these modules are indeed using the AWS provider
- It looks like each terraform-ls instance is ion average 200MB as you mention - good to know I am similar to others!

Maybe nothing has changed, and I am just more sensitive (although the 20+ terraform/aws folder workspace is definitely not usable any more)

I will close this issue, and follow #482 as that will address my issues I think

Finally, thanks for all the work on the language server, makes Terraform a lot of fun to develop with!

Cheers

Rich
