### ISSUE TITLE
Publish release binaries to releases.hashicorp.com

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#49]
In addition to the GitHub release.

We should also build the JSON index as well to determine latest version.

**Comment by radeksimko** [comment]
I'd expect `hc-releases` here to do most of the hard work (including the index building?), but I'm not that familiar with it, so I'll need to read through the implementation/docs.

We could plug it into the existing GitHub Action either as a next step after GoReleaser, or send a patch to GoReleaser to support global post hooks, similar to pre-hooks: https://goreleaser.com/customization/#Global%20Hooks
and then plug it in there.

**Comment by paultyng** [comment]
I think probably easiest to just chain it afterwards in the GitHub action unless there is some context you'd want to reuse that goreleaser would provide?

**Comment by radeksimko** [comment]
The benefit of reusing GoReleaser pipeline is that we could publish Homebrew/Scoop formula with our releases.hashicorp.com URLs, which make it much easier for us to track downloads in much more detailed way - including the ability to segment downloads via Homebrew or Scoop.

Technically we could do that even without any GoReleaser patches, but we'd be publishing Homebrew/Scoop updates before the binaries are actually uploaded and available, which is a bit awkward.

Download tracking via GitHub API is currently _very minimal_ as it doesn't go beyond a single number representing total download count 😑 , so we wouldn't be able to identify Homebrew or Scoop downloads that way and tracking weekly or monthly downloads would also be more difficult.

**Comment by radeksimko** [comment]
I created https://github.com/goreleaser/goreleaser/issues/1460 to gather some preliminary feedback on a potential upstream patch that could support this integration.
