### ISSUE TITLE
v0.17.0 missing release notes

### ISSUE THREAD

**Issue by meldron** [hashicorp/terraform-ls#533]
Can you please add the release notes / change log for https://github.com/hashicorp/terraform-ls/releases/tag/v0.17.0

I'm always a little bit disappointed when an extension says hey open link to view release notes and then they are missing. :smile: 

Keep up the great work!

Thanks alot!

**Comment by radeksimko** [comment]
Thank you for noticing @meldron 

Unfortunately [we don't have that process automated yet](https://github.com/hashicorp/terraform-ls/issues/63) and I forgot to do this manually yesterday.

It should be updated now.

**Comment by meldron** [comment]
That was fast! Thanks a lot!
