### ISSUE TITLE
Go to (local) module implementation from `source`

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#558]
### Use-cases

See https://github.com/hashicorp/vscode-terraform/issues/669

### Notes

One would be tempted to use the "go to implementation" LSP method for this but according to how it is implemented in VS Code, this may **not** be the appropriate use.

![Screenshot 2021-06-18 at 15 43 26](https://user-images.githubusercontent.com/287584/122579508-e4d22000-d04c-11eb-8c67-c6da796f8d4e.png)

It seems that this is meant to be used in contexts of "interface implementations" in languages that have interfaces, hence the plural.

#### Go To Definition

Use native [`textDocument/definition`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition) method to associate module URIs with relevant `source` attribute values.

This will be surfaced as Cmd/Ctrl+click-able and via context menu in most IDEs.

**Comment by dbanck** [comment]
Might be related / required: https://github.com/hashicorp/terraform-ls/issues/674
