### ISSUE TITLE
100% CPU and Memory usage since 0.18.2

### ISSUE THREAD

**Issue by ElvenSpellmaker** [hashicorp/terraform-ls#573]
### Server Version
```
0.18.2
```

Last Known Working version: 0.18.1

### Terraform Version

```
0.13.1
```

### Client Version

```
VSCode 1.57.1
```

### Terraform Configuration Files
N/A I think

### Log Output
Logging for starters throws an error using the default on the troubleshooting page `Failed to setup logging for Terraform: template: tf-log-file:1: function "lsPid" not defined`.

Either way I've tried to get the CPU and Memory logs and it never seems to generate any files (it was generating some 0 but CPU files but never populated them)

It generates the normal language server which ends with a lot of Receiving 1 notification:
```
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:15 server.go:591: Received 1 new requests
2021/07/01 22:40:39 server.go:591: Received 1 new requests
2021/07/01 22:40:39 server.go:591: Received 1 new requests
2021/07/01 22:40:47 server.go:591: Received 1 new requests
2021/07/01 22:40:47 server.go:591: Received 1 new requests
2021/07/01 22:40:52 server.go:591: Received 1 new requests
2021/07/01 22:40:57 server.go:591: Received 1 new requests
```

And then stops.

### Expected Behavior
VsCode to behave as usual

### Actual Behavior
Memory and CPU spiral out of control almost making the system unusable. Killing the `terraform-ls` binary causes it to temporarily drop down.

### Steps to Reproduce
`code .` with a project that contains terraform, within a few seconds of going to a tf file the CPU and memory will have spiralled out of control.

**Comment by lysacor** [comment]
I am seeing the same behavior

**Comment by KyleKotowick** [comment]
Confirmed, it just crashed my comp with 64GB RAM when I tried to save 3 open files. This is a critical bug.

**Comment by ElvenSpellmaker** [comment]
@KyleKotowick Hey, I went to the location of the language server and in there was one exe and two zips. Delete the language server exe and then go to the 0.18.1 zip and extract the file out.

You'll know be back on 0.18.1 and ignore vscode trying to uodate it.

**Comment by radeksimko** [comment]
Hi folks,
Sorry for any inconvenience.

Can any of you share any more details? Namely:
 - configuration that triggers this, and/or
 - beginning of the log (from `Launching language server:`), or ideally just whole log

![Screenshot 2021-07-02 at 09 10 18](https://user-images.githubusercontent.com/287584/124243082-56ae6d00-db15-11eb-939b-81659a40a78b.png)

I was not able to reproduce this unfortunately.

**Comment by ElvenSpellmaker** [comment]
Hey @radeksimko The most useful logs, Memory, CPU, and TF Logs don't generate at all. The main log doesn't have any errors in it, it just seems to opening files by scanning the whole repo.

If there's any way I can get more detailed logs then I could try, I tried turning on `trace.server` option in vscode but to no avail.

It just seems to load some modules in the repo up and then spirals out of control.

**Comment by radeksimko** [comment]
> The main log doesn't have any errors in it, it just seems to opening files by scanning the whole repo.

I don't expect it to have errors, based on the snippet above but it would help to know what happens after the launch and which requests are and are not processed. Do you mind sharing the relevant part of the log?

> Memory, CPU, and TF Logs don't generate at all

Both CPU & memory profiles are written into after the shutdown of the process - which should happen automatically if you shut down VS Code. It is also worth mentioning that if you have multiple folders in your workspace then each folder would be served by a different LS process and so the flags should use the templating (such as `{{pid}}`) to allow collecting profiles per process and avoid processes writing into the same file over each other.

https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#cpu-profiling
https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#memory-profiling

Thanks.

**Comment by ElvenSpellmaker** [comment]
I tried to get the logs to generate but vscode doesn't generate them using 0.18.2 even after shutdown of vscode.

**Comment by radeksimko** [comment]
@ElvenSpellmaker Do you mind sharing the configuration, so I can try reproducing it myself?

You may also [encrypt it](https://keybase.io/radeksimko) and/or send it privately to `radek<at>hashicorp.com` if you prefer.

**Comment by ElvenSpellmaker** [comment]
@radeksimko I'll send the logs for 0.18.1 and 0.18.2 to your e-mail, they're not super private, but it'd be easier that way. 🙂

**Comment by radeksimko** [comment]
@ElvenSpellmaker was kind enough to provide a working repro case privately.

I am still investigating the root cause, but I have some confidence to say that this is being triggered by some nested objects, such as

```hcl
locals {
  top_obj = {
    first = {
      attr = "val"
    },
    second = {
      attr = "val"
    },
    third = {
      attr = "val"
    },
    fourth = {
      attr = "val"
    },
  }
}
```
^ that is the most minimal snippet I was able to extract and still reproduce the bug

Thank you for your patience.

**Comment by radeksimko** [comment]
Thank you @ElvenSpellmaker for the report and for helping to reproduce this.

It is fixed in `0.18.3` which was just released.

VS Code should prompt you to upgrade upon next launch or in the next 24 hours.

**Comment by ElvenSpellmaker** [comment]
@radeksimko Excellent, thanks Radek!

**Comment by ElvenSpellmaker** [comment]
I can confirm the newer version seems to have patched the issue.
