### ISSUE TITLE
Go to definition of variable value in `tfvars`

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#581]
### Use-cases

From 0.19 users are able to go to variable definition/declaration, which is always considered to be the `variable` block (where value can be specified as `default`).

In Terraform it is also possible to specify value of a variable via tfvars file and users would benefit from being able to find the value definition of a variable from its reference (e.g. `var.foo`).

### Proposal

TODO

**Comment by danishprakash** [comment]
hey @radeksimko, this looks like an interesting one, mind If I take a shot at it?

**Comment by radeksimko** [comment]
After thinking through this and trying to map LSP's concepts somehow to HCL I believe we should represent tfvars entries as _references_, rather than _definitions_ for variable blocks, which is already tracked under https://github.com/hashicorp/terraform-ls/issues/618

The minor difference this will make is that users would pick a different item from the context menu
<img width="381" alt="Screenshot 2021-09-30 at 11 47 00" src="https://user-images.githubusercontent.com/287584/135441582-6d5e769d-d6ef-40bd-b330-18269e196a77.png">

This also reflects the fact that VS Code implements UX aspect of go-to-definition as Ctrl/Cmd+click and making a `variable` block clickable would be slightly awkward.

The opposite should work though - i.e. tfvars entry would be considered a reference to the `variable` block, and so Ctrl/Cmd+click-ing on a `tfvars` entry will take you to the block (not the opposite, which is what this issue was proposing). Relatedly `Go to Definition` from `tfvars` would take you to the relevant `variable` block.
