### ISSUE TITLE
curly braces does not autocomplete in .tfvars files

### ISSUE THREAD

**Issue by benhurjoel** [hashicorp/terraform-ls#586]
### Server Version
2.13.1

### Terraform Version
1.0.1

### Client Version

VS Code 1.58.2

### Terraform Configuration Files
![image](https://user-images.githubusercontent.com/57881441/125975823-775fb13b-1709-48cf-b549-be6fd6ac9a56.png)

### Expected Behavior
Curly braces should get autocompleted

### Actual Behavior
Nothing happens. Have to manually close the bracket.

### Steps to Reproduce
It simply does not work in any TFVARS file. I have installed Azure Tools plugin as well (not sure if that's what causing the problem)

**Comment by radeksimko** [comment]
We currently don't provide completion or any other features within `tfvars` which aren't auto-loaded yet.

That feature is however on the near-term roadmap and is already tracked under https://github.com/hashicorp/terraform-ls/issues/562

Do you mind me closing this issue in favour of #562 ?

**Comment by benhurjoel** [comment]
Thank you @radeksimko for your response. 

Closing this case in favor of #562 .
