### ISSUE TITLE
Go to References not working case

### ISSUE THREAD

**Issue by Chupaka** [hashicorp/terraform-ls#592]
### Server Version

```
terraform-ls 0.19.1
```

### Terraform Version

```
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.75.0
```

### Client Version

```
VS Code 1.58.2
HashiCorp Terraform v2.13.1
```

### Terraform Configuration Files

```hcl
variable "test2" {
  default = "mynameis"
}

resource "google_compute_instance" "checking" {
  name = "test"
  machine_type = "fake"
  network_interface {}
  boot_disk {
    initialize_params {
      image = "img"
    }
  }

  metadata = {
    "startup-script" = var.test2
  }
}

```

### Log Output
```
2021/07/23 15:03:27 server.go:591: Received 1 new requests
2021/07/23 15:03:27 server.go:175: Processing 1 requests
2021/07/23 15:03:27 server.go:266: Checking request for "textDocument/references": {"textDocument":{"uri":"file:///Users/pavel.skuratovich/tmp/go-to-reference/file1.tf"},"position":{"line":1,"character":11},"context":{"includeDeclaration":true}}
2021/07/23 15:03:27 rpc_logger.go:29: Incoming request for "textDocument/references" (ID 36): {"textDocument":{"uri":"file:///Users/pavel.skuratovich/tmp/go-to-reference/file1.tf"},"position":{"line":1,"character":11},"context":{"includeDeclaration":true}}
2021/07/23 15:03:27 provider_schema.go:196: PSS: getting provider schema (/Users/pavel.skuratovich/tmp/go-to-reference, registry.terraform.io/-/google, )
2021/07/23 15:03:27 references.go:60: finding origins for inner-most target: &lang.ReferenceTarget{Addr:lang.Address{lang.RootStep{Name:"var"}, lang.AttrStep{Name:"test2"}}, ScopeId:"variable", RangePtr:(*hcl.Range)(0xc00863b1c0), Type:cty.String, Name:"", Description:lang.MarkupContent{Value:"", Kind:0x0}, NestedTargets:lang.ReferenceTargets(nil)}
2021/07/23 15:03:27 rpc_logger.go:50: Response to "textDocument/references" (ID 36): []
2021/07/23 15:03:27 server.go:247: Completed 1 requests [2.717054ms elapsed]
```

### Steps to Reproduce

Click line 1-3 and select "Go to References"

### Expected Behavior

Jump to line 16 (`n"startup-script" = var.test2`)

### Actual Behavior

`No references found for 'test2'`

## Linked issues
#585

**Comment by radeksimko** [comment]
Thank you for the detailed repro case, as usual @Chupaka 

I just merged a fix in #596 which will be shipped early next week.

**Comment by Chupaka** [comment]
@radeksimko looks like v0.20 broke something, as now the var in `"startup-script" = var.test2` not even highlighted when I press Cmd. And it is highlighted in other places of code (for example, when I change `name = "test"` to `name = var.test2`)

**Comment by radeksimko** [comment]
That is possible - there were some changes in how the expressions are parsed, (ironically) making it a more accurate - which in combination with collection of references being inaccurate caused mismatch of types and the reference not being recognized.

That should be fixed in the next release coming early next week.

**Comment by radeksimko** [comment]
`0.20.1` was just released and should address both mentioned issues.

**Comment by Chupaka** [comment]
Yep, it does! Now terraform-ls looks perfect for me, thanks @radeksimko!
