### ISSUE TITLE
Generate variable from terraform module

### ISSUE THREAD

**Issue by nicholastcs** [hashicorp/terraform-ls#597]
### Use-cases
**Persona:** 
Software Developers (generally non-Terraform practitioners) who has minimum knowledge of what Terraform does, at minimum able to interact with Terraform module.

**Use case:**
Software developers able to retrieve module variable automatically without go through documentation.

**High-level goal:** 
Enablement of self-serve infrastructure (SSI) for software developers and speed up adoption of developer maintained Terraform codes. 

### Attempted Solutions
So far, none. Software developers had to read through the documentation in Readme.MD and piece the variables in the module together, which takes significant amount of time and hassle.

### Proposal
Example an implementation terraform module:
```
module "ecs_service" {
  source = "..."
  
}
```
Perhaps software developers may use certain hotkeys, Terraform-LS automagically generate the variables...
```
module "ecs_service" {
  source = "..."
  
  # required
  project_name = string
  environment  = string
  service_name = string

  # optional
  type                  = "application"
  environment_variables = {}
  command               = null
  cpu                   = 1024
  memory                = 2048
  ...
}
```

**Comment by radeksimko** [comment]
Hi @nicholastcs 
It seems to me that you're looking for a feature that is already implemented and was just very recently released as part of https://github.com/hashicorp/terraform-ls/pull/551 (0.20.0)

Am I right?

I should mention though that recognition of inputs or outputs for a module call currently requires the module to be installed, i.e. `terraform get` to run. We plan to make some improvements in that area though, see the following issues:

 - https://github.com/hashicorp/terraform-ls/issues/598
 - https://github.com/hashicorp/terraform-ls/issues/599

**Comment by nicholastcs** [comment]
Hi @radeksimko 

Yes, you are right, I'll try the new 0.20.0 terraform-ls. Thanks for letting me know.

In the future, is it possible to not require developer to download Terraform and infer the variables through language server?

You may close the issue if you found it to be a duplicate of other issue. 

Thanks.

**Comment by radeksimko** [comment]
> In the future, is it possible to not require developer to download Terraform and infer the variables through language server?

Yes, that is basically the plan, although the solution will differ depending on where you host your module. For modules linked locally within the repo/filesystem via `./path` https://github.com/hashicorp/terraform-ls/issues/598 will address that.

For remote modules hosted in the [Terraform Registry](https://registry.terraform.io) we plan to obtain the metadata via relevant API, as per https://github.com/hashicorp/terraform-ls/issues/599

Any other modules will however require `terraform get` as there is no reliable/reasonable way of obtaining the metadata without actually installing the module - which is exactly what `terraform get` does.

**Comment by nicholastcs** [comment]
Hi @radeksimko ,

I've tried out the feature at 0.20.0, #551. It is working as it should be with `terraform get` or `terraform init`.

Thanks on developing the terraform-ls, making adoption easy for developers.
