### ISSUE TITLE
local variables autocomplete not working within inline block

### ISSUE THREAD

**Issue by softveda** [hashicorp/terraform-ls#600]
Extension Version: v2.14.0
Terraform version: 
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.52.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

Code in Module, main.tf

``` tf
provider "aws" {
  region = "ap-southeast-2"
}

locals {
  http_port     = 80
  any_port      = 0
  any_protocol  = "-1"
  tcp_protocol  = "tcp"
  http_protocol = "HTTP"
  all_ips       = ["0.0.0.0/0"]
}
```

The auto complete for local variables didn't work inside the ingress and egress inline blocks.

``` tf
resource "aws_security_group" "alb" {
  name = "terraform-example-alb"

  ingress {
    description = "Allow HTTP inbound"
    cidr_blocks = local.all_ips
    from_port   = local.http_port
    to_port     = local.http_port
    protocol    = local.tcp_protocol
  }

  egress {
    description = "Allow All outbound"
    cidr_blocks = local.all_ips
    from_port   = local.any_port
    to_port     = local.any_port
    protocol    = local.any_protocol
  }
}
```

<img width="491" alt="Screen Shot 2021-08-02 at 8 49 41 pm" src="https://user-images.githubusercontent.com/1845906/127850564-263a10c2-92d7-4d7b-838a-56886899d36a.png">

Autocomplete works here though. Also notice how the keyword "local" has different colour between the two places.

``` tf
resource "aws_lb_target_group" "asg" {
  name     = "terraform-asg-example"
  port     = var.server_port
  protocol = local.http_protocol
  vpc_id   = data.aws_vpc.default.id

  health_check {
    path                = "/"
    protocol            = local.http_protocol
    matcher             = "200"
    interval            = 15
    timeout             = 3
    healthy_threshold   = 2
    unhealthy_threshold = 2
  }
}
```

<img width="477" alt="Screen Shot 2021-08-02 at 8 54 17 pm" src="https://user-images.githubusercontent.com/1845906/127851084-83621621-e988-42e8-b0ec-ce945720b6b7.png">

**Comment by radeksimko** [comment]
Reproduced, thank you for the report.

I have transferred this over to the language server repository as LS is responsible for parsing the configuration.

From a brief investigation I can tell that `aws_security_group` uses a special ["compatibility mode"](https://github.com/hashicorp/terraform-provider-aws/blob/236172f78e8ce7813ab26fe1338a4971e4594d33/aws/resource_aws_security_group.go#L85) for the `ingress` and `egress` blocks, which effectively makes them available as attributes. There are other differences, but to put it simply attributes have the `=` (equal sign) after the name, blocks do not.

The extension & language server should understand _any_ valid configuration so this is certainly a bug.

I am talking to the SDK team internally to first understand how exactly should the compatibility mode work and which one is the preferred representation of the config.

In the meantime though you may be able to work around this by adding `=` after `ingress` and `egress`.

**Comment by radeksimko** [comment]
It is my understanding that attributes (i.e. `ingress = [{ ... }]` and `egress = [{ ... }]`) is the preferred way of expressing these fields, which is also why I proposed some changes to the relevant docs: https://github.com/hashicorp/terraform-provider-aws/pull/20428

#607 will make it possible for the language server to recognize these fields as blocks too, but it would prefer completion of attributes if you trigger it within the resource body.
