### ISSUE TITLE
Support multiple validation blocks during completion for variable block

### ISSUE THREAD

**Issue by seandockery** [hashicorp/terraform-ls#609]
The `variable` block can accept multiple `validation` blocks in terraform files.  However, after I declare a `validation` block inside a `variable` block, completion in vscode does not offer `validation` again in the same `variable` block.  I can work around the issue by deleting other `validation` blocks temporarily, but it would be nice if that wasn't necessary.  I am using v2.14.0 of the HashiCorp Terraform extension.  Thanks!

**Comment by radeksimko** [comment]
Good catch - thank you for the report @seandockery 

You are right indeed that multiple validation blocks are allowed/expected:
https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/configs/named_values.go#L132-L138

and you're also right about the place where this can be fixed. 😄 

I just patched it upstream and raised https://github.com/hashicorp/terraform-ls/pull/610

Additionally this fact also doesn't seem very obvious from the docs here:
https://www.terraform.io/docs/language/values/variables.html#custom-validation-rules
so I submitted a patch for these docs too: https://github.com/hashicorp/terraform/pull/29299
