### ISSUE TITLE
Create Terraform Module Source Address parsing library

### ISSUE THREAD

**Issue by jpogran** [hashicorp/terraform-ls#647]
Extract (in the form of some re-implementation and copy-pasting) the detection logic from Terraform Core  https://github.com/hashicorp/terraform/blob/332ea1f233891e45bd274e714ab8e4e11c79dc95/internal/addrs/module_source.go#L191-L268

The implementation doesn't have to be perfect nor it needs to cover 100% of cases that Terraform Core covers, as it's meant to be mostly UX improvement picking a particular icon, not a critical part of the API, but I think we should at least attempt to mimic what core does. Improving the detection later should also be relatively easy given the testability of something that takes just single string as input.

_Originally posted by @radeksimko in https://github.com/hashicorp/terraform-ls/pull/632#discussion_r714722988_

**Comment by dbanck** [comment]
Closed via https://github.com/hashicorp/terraform-registry-address/pull/7
