### ISSUE TITLE
Doubly-unescaped URI causing workspace to be ignored

### ISSUE THREAD

**Issue by CraigStuntzWillowTree** [hashicorp/terraform-ls#655]
## Versions

This bug is reproducible in:
 - [ X ] the **latest** version of the extension (below)
 - [ X ] the **latest** version of the language server (below)

### Extension

```
v2.14.0
```

### Language Server

```
2021/09/13 16:25:30 serve_command.go:162: Starting terraform-ls 0.21.0
```

### VS Code

```
Version: 1.59.1
```

### Operating System

```
macOS 11.6
```

### Terraform Version

```
v0.14.7
```

### Steps To Reproduce

Run VS Code.
See dialog box pop up with the error displayed.

![image](https://user-images.githubusercontent.com/71773805/133466503-8d25c541-d31f-4743-9c5f-83fb2dd0f52b.png)

```
Ignoring workspace folder file:///Users/craig/Documents/ab/AB%2520Manager%2520Portal: lstat /Users/craig/Documents/ab/AB Manager Portal: no such file or directory. This is most likely bug, please report it.
```

The folder does exist (see screenshot). However, the displayed path is incorrect `%2520` instead of `%20`

### Expected Behavior

No error
### Actual Behavior

Error displayed.

**Comment by radeksimko** [comment]
We made some significant changes to how URIs are parsed as part of https://github.com/hashicorp/terraform-ls/pull/771

This means that we should no longer be double-escaping or double-unescaping any URIs.

That said URI escape sequences such as `%20` are generally problematic and don't seem to play well with Terraform's other internals, or possibly with Windows FS - or the part of Windows FS API which Go interacts with. As you can see below, `terraform init` of a module with `source = "./With%20Escaped%20Spaces"` will return error.

![2022-03-14 14 41 51](https://user-images.githubusercontent.com/287584/158196573-696368b9-a13e-45b9-a353-ed76ed9e8be5.gif)

That said the language server can now provide IntelliSense within the module, assuming that is a stand-alone module which - for any reason - still has `%20` in the path.
![2022-03-14 14 51 21](https://user-images.githubusercontent.com/287584/158197777-472da289-e849-4064-aeb9-5b63905a0fcd.gif)
