### ISSUE TITLE
formatOnSave not honoured/working on ,tf files

### ISSUE THREAD

**Issue by rbtcollins** [hashicorp/terraform-ls#669]
### Server Version

```
$ terraform-ls --version
terraform-ls: command not found
```

### Terraform Version

```
$ terraform -v
Terraform v1.0.8
on linux_amd64
```

### Client Version

```
vscode 1.60.2
```

### Expected Behavior

Installing the terraform extension in VS Code should be enough to have it work.

### Actual Behavior

No errors were reported by VS Code (in the sense of notification bubbles), but saved files were not formatted.

### Steps to Reproduce

1. Install vscode in a brand new user - no existing settings.
2. Install the terraform extension
3. Open a directory with .tf files
4. Open a .tf file
5. Add a space somewhere that changes the content to be unformatted but still legitimate .tf
6. Save the file

**Comment by radeksimko** [comment]
Hi @rbtcollins 
It looks like we completely forgot about this older issue! Sorry about that.

Either way, the auto-formatting in VS Code should work, as long as the appropriate settings is in place. We have some documentation available under https://github.com/hashicorp/vscode-terraform#formatting

If you can confirm that these settings are in place and formatting still doesn't work I would encourage you to file a new issue and attach all the relevant settings + ideally the log output.

Thanks!
