### ISSUE TITLE
Repurpose `rootModulePaths` and `excludeRootModulePaths`

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#704]
The following config options should not be needed and if they are then we can direct people to the native LSP feature workspace folders, which we treat pretty much the same way already. If a client doesn't support that feature then this may help encourage the client to implement it. 🤷🏻 

https://github.com/hashicorp/terraform-ls/blob/91ba27b71f309c64fd0bff399bfe52824d71a192/internal/settings/settings.go#L19-L21

https://github.com/hashicorp/terraform-ls/blob/91ba27b71f309c64fd0bff399bfe52824d71a192/internal/langserver/handlers/initialize.go#L212-L226

**Comment by radeksimko** [comment]
https://github.com/hashicorp/terraform-ls/issues/724 may need to be implemented first to ensure that adding a workspace with uninitialized module also gets it indexed and therefore would be comparable to `rootModulePaths`

**Comment by jpogran** [comment]
We can add `deprecated` to the client settings in VS Code so users know this is coming while we work on the above.
