### ISSUE TITLE
Completions include full resource path

### ISSUE THREAD

**Issue by sblask** [hashicorp/terraform-ls#708]
### Server Version

```
$ terraform-ls --version
0.24.0
```

### Terraform Version

```
terraform --version
Terraform v1.0.11
on darwin_amd64

```

### Client Version

```
$ nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```

### Terraform Configuration Files

```hcl
data "aws_s3_bucket" "test" {
  bucket = "test"
}

data "aws_s3_bucket" "test2" {
  bucket = "test2"
}

locals {
  name = data.
}

```

### Actual/Expected Behavior
I only just started with terraform-ls and LSP in general and I am not exactly sure what is supported, but when i put my cursor after `data.` and try to complete, I get `data.aws_s3_bucket.test` as suggestion and when I choose the item I end up with `data.data.aws_s3_bucket.test` (two `data`) and can't complete further because there is no match. I'd kind of expect `aws_s3_bucket` as suggestion only, maybe `aws_s3_bucket.test` and `aws_s3_bucket.test2`, and that completing would actually result in `data.aws_s3_bucket.test`. Possibly related: if I try to complete on `data.a` I don't get any suggestions. When trying the same kind of completion in Python everything behaves as expected, so I don't think it's my vim config?

**Comment by radeksimko** [comment]
Hi @sblask 
It would be helpful to have log at hand to confirm by assumptions below - can you collect it, please?
https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#logging

I have a reason to believe that NeoVim (or rather the LSP implementation within) misinterprets the range to which it's supposed to apply textEdit when it comes to a scenario like this.

I noticed the same behaviour when debugging a different problem in https://github.com/hashicorp/terraform-ls/issues/691#issuecomment-957306612

**Comment by alexaandru** [comment]
FWIW the sample above works as expected for me, with the nightly Neovim: no duplicate `data.data`. But I don't use any completion plugins, only the omnicomplete, provided by neovim/LSP (I trigger it with <C-x><C-o>). So perhaps before looking at Neovim (or terraform-ls) for the issue, is worth looking at the completion plugin you are using...?

You can use the following minimal config to take your own .vimrc (and any associated plugins) out of the equation:

```Lua
require"lspconfig".terraformls.setup{}
vim.o.omnifunc = "v:lua.vim.lsp.omnifunc"
```
then, run `nvim -u tf.lua main.tf` (where `tf.lua` holds the above "vimrc replacement" and `main.tf` holds the TF sample above mentioned). Then just use omnicomplete to do the completion. If that works, then this is neither a neovim nor a terraform-ls issue.

Hope it helps!

**Comment by sblask** [comment]
I am not using a completion plugin either and the above also failed for me using Neovim 0.5. However, trying with the latest nightly all the problems disappeared. So it seems to be a Neovim problem that is already fixed. Thanks for pointing me in the right direction. @radeksimko if you still want the log, I can look into it, but it seems like the problem from the other issue is unrelated because they are already using Neovim 0.6?

**Comment by alexaandru** [comment]
You're most welcome! Cheers!
