### ISSUE TITLE
Switch to hc-install from tfinstall

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#711]
### Use-cases

The part of tfexec library we use - tfinstall - responsible for installing Terraform in a few contexts - was extracted into a more generalized library https://github.com/hashicorp/hc-install

Upcoming release of tfexec will have tfinstall removed and we should migrate to hc-install for installation.

### Proposal

Find usage of tfinstall and replace the logic with equivalent hc-install logic.

**Comment by rtim75** [comment]
Does anyone mind if I pick this one up?

**Comment by radeksimko** [comment]
@rtim75 Feel free to pick it up! 👍🏻
