### ISSUE TITLE
refactor job scheduler to make it easier to test

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#719]
## Problem Statement

Currently we have at least one test which has to have `time.Sleep` due to the fact that we run certain operations in `Defer` which is in a separate goroutine and we don't have any synchronization to allow the test to wait for the completion.

Ideally tests should not have to implement `time.Sleep` to test regular scenarios with multiple modules.

https://github.com/hashicorp/terraform-ls/blob/371d8fdb3664c8b036fdff2b2bef4040498385c6/internal/langserver/handlers/complete_test.go#L720-L724

## Requirements Summary

The scheduler has a number of requirements:

 - testability (as mentioned above)
 - progress reporting - to be able to inform user of the progress in the UI
 - dependent tasks - e.g. ensure that decoding for a particular module runs _after_ parsing
 - priorities - ensure that jobs scheduled from `didOpen` or `didChange` events are not affected by background indexing workload of a large workspace
 - deduplication - to avoid indexing the same document/module version twice (from workspace indexing vs didOpen/didChange handlers)
 - querying task status - e.g. be able to block in didOpen/didChange/... handlers until essential jobs finish, to avoid sync issues in other handlers (e.g. completion)
 - ability to add or remove jobs affecting a particular path from queue before processing - e.g. when `workspace/didChangeWorkspaceFolders` is received

## Proposal

In order to be able to effectively sort tasks (based on dependencies or document state open/closed), dequeue tasks by path and block in handlers, it would be reasonable to store certain data in memdb. Two new tables are proposed for creation.

### `documents`

Currently documents metadata is stored as a map and is tightly coupled with the `filesystem` package:
https://github.com/hashicorp/terraform-ls/blob/88734ad1e2ff93c4963f28b13dc51acdc593cad7/internal/filesystem/filesystem.go#L20-L21

A new memdb table can be created within `state` package to hold the following structure:

```go
type Document struct {
	Path       string
	LanguageID string
	Version    uint
	IsOpen     bool
	Content    source.Lines // or []byte or both
}
```

### `jobs`

Currently job data is maintained as a queue (internally a slice) within the `terraform/module` package:
https://github.com/hashicorp/terraform-ls/blob/main/internal/terraform/module/module_ops_queue.go

A new memdb table can be created within `state` package to hold the following structure:

```go
type Job struct {
	ID      uint
	DirPath string
	State   uint // Queued / Running / Done
	Func    func()
	Type    string // e.g. GetTerraformVersion; mainly for stats collection
}
```

The same `"jobs"` table can hold jobs submitted "on the background" from the watcher/walker _and_ from `didOpen`/`didChange` handlers, to enable deduplication. Two different "indexer" implementations can be exposed with different criteria of how to pull the next (if any) job from the table.

## Notes / Open Questions

 - Could memdb "watchers" be used in tests and in handlers where we need to block?
 - Main exec loop can use [`txn.FirstWatch`](https://pkg.go.dev/github.com/hashicorp/go-memdb#Txn.FirstWatch) method to block until next job is available

**Comment by dbanck** [comment]
Just a quick thought: I've used a couple of queuing/scheduling libraries with other programming languages. Most of them are well-architected and support all listed requirements. It might be worth checking out if there is something for Go, too, which we can leverage?

**Comment by radeksimko** [comment]
> It might be worth checking out if there is something for Go, too, which we can leverage?

I did actually use one library early on, but it didn't support priority queues. https://github.com/hashicorp/terraform-ls/commit/ef82870078a90aa2d8fc8f0d814e35e81d872ad6 but there isn't that many out there that I'm aware of. This is probably because Go actually offers decent primitives in the standard library (go routine + synchronization via `sync` package).

With the above proposal though the requirements apply to the whole solution, but lots of them are in fact satisfied by memdb, which means that the implementation of the scheduler can be relatively simple - all it needs to know is what the "next" job is and run that job in a go routine.

Much of the existing complexity IMO comes from wanting to satisfy all the requirements within the scheduler and I'm hoping to get rid of that complexity by decoupling the code, as proposed.
