### ISSUE TITLE
textDocument/definition returns targetSelectionRange with a start and end of (0,0).

### ISSUE THREAD

**Issue by seanlynch** [hashicorp/terraform-ls#735]
Apologies for the lack of detail; I encountered this on a machine I cannot log into my personal Github account from.

### Server Version
0.25.0

### Terraform Version
1.0.3

### Client Version
emacs-lsp

### Terraform Configuration Files
Shouldn't be relevant

### Log Output
Hopefully not needed

### Expected Behavior
According to the spec, targetSelectionRange must contain targetRange. So I expect that to be the case.

### Actual Behavior
targetSelectionRange has a start and end at line 0 column 0, which does not contain targetRange.

### Steps to Reproduce
Set up terraform-ls with emacs-lsp and try to go to a definition with `lsp-find-definition`.

**Comment by seanlynch** [comment]
The relevant section of the LSP spec:

	/**
	 * The range that should be selected and revealed when this link is being
	 * followed, e.g the name of a function. Must be contained by the the
	 * `targetRange`. See also `DocumentSymbol#range`
	 */

**Comment by radeksimko** [comment]
Good catch, thank you for the report.

It looks like this was just missed in the recent refactoring in 0.24.0+

https://github.com/hashicorp/terraform-ls/commit/6fb9f47d91979639a420d2e0611639a6c2b01c17#diff-b369d9fbb9324988bd48fac32b664e430f1d06101dd0307d7574e47b69d790ddL25

I will raise a PR with patch.
