### ISSUE TITLE
Is storage_account_name required on azurerm_function_app?

### ISSUE THREAD

**Issue by vanmash** [hashicorp/terraform-ls#744]
### Server Version

```
Terraform Visual Studio Code Extension v2.17.0
```

### Terraform Version

```
Terraform v1.1.2
on windows_amd64
```

### Client Version

```
VS Code 1.63.2
```

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "func" {
  name                       = "func"
  location                   = azurerm_resource_group.rg.location
  resource_group_name        = azurerm_resource_group.rg.name
  app_service_plan_id        = azurerm_app_service_plan.asp.id
  storage_account_name       = azurerm_storage_account.st.name
  storage_account_access_key = azurerm_storage_account.st.primary_connection_string
}
```

### Expected Behavior

Accounting to azurerm_function_app [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#storage_account_nam) `storage_account_name` and `storage_account_access_key` are Required. Terraform Visual Studio Code Extension shows them as Optional (in tool tip)

### Actual Behavior

`storage_account_name` and `storage_account_access_key`  should be shown as Required. 

### Steps to Reproduce

1. move mouse pointer over `storage_account_name`
2. wait for a tool tip

**Comment by radeksimko** [comment]
I suspect this may/will differ between provider versions, but the latest published version (2.90.0) still seems to treat the field as optional currently:
https://github.com/hashicorp/terraform-provider-azurerm/blob/ab515ef6918b51afd2ef5296a05653ccf9cecb5c/internal/services/web/function_app_resource.go#L179-L180

So I would say the documentation is incorrect - can you bring this up in https://github.com/hashicorp/terraform-provider-azurerm ?

--- 

Also it may be confusing but keep in mind that some providers may sometimes use "optional" for fields which are "effectively required" in situations where these fields would conflict with some other ones. In other words the providers do not (yet) have an effective way to communicate "one of these fields is required" and so some fields will just show up as optional.

In either case what you see in the hover tooltip should reflect the latest published provider version at the time of the LS release, or locally installed provider.
