### ISSUE TITLE
Strange color highlighting 

### ISSUE THREAD

**Issue by lego963** [hashicorp/terraform-ls#763]
## Versions

This bug is reproducible in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension

```
HashiCorp Terraform
v2.14.0
```

### Language Server

```
Starting terraform-ls 0.21.0
```

### VS Code

```
1.60.0
```

### Operating System

```
Linux vrnnb-prc480 5.10.16.3-microsoft-standard-WSL2 hashicorp/vscode-terraform#1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux
```

### Terraform Version

```
Terraform v1.0.6
on linux_amd64
```

### Actual Behavior
![image](https://user-images.githubusercontent.com/17201690/132822514-b47a9d61-1fd9-40a7-b7bd-982dba705e68.png).

```tf
variable "read_replica_config" {
  type = list(
    object(
      {
        name                 = string,
        flavor               = string,
        availability_zone    = string,
        public_ips           = list(string),
        volume_type          = string,
        volume_encryption_id = string
      }
    )
  )
  description = "(optional)"
}
```
 

Reference: https://github.com/ansible/vscode-ansible/issues/175 (Maybe?)

**Comment by radeksimko** [comment]
I wasn't able to reproduce the problem using the original configuration but I found another snippet which does reproduce the same problem (in the latest version of LS & VSCode extension):

```hcl
variable "test" {
  type = object({
    test_object = map(
      object({
        test_map = string
      })
    )
  })
}

output "test" {
  value = var.test
}
```
<img width="253" alt="Screenshot 2022-03-01 at 21 02 58" src="https://user-images.githubusercontent.com/287584/156248451-7809c3e5-98ae-4b0c-a907-dc4a2817f631.png">

related debug log:
https://gist.github.com/radeksimko/8f4035c7bfb7f5b11bd4ea4b1e83931d

It is possible that offsets/ranges to which semantic tokens are being applied are miscalculated somehow somewhere. The above now appears consistently reproducible upon reload of VSCode - which also suggests that outdated tokens are not a factor (also less likely after https://github.com/hashicorp/terraform-ls/pull/630 anyway), so I can look into this more closely.
