### ISSUE TITLE
ctxTfSchemaReader may error with the value 

### ISSUE THREAD

**Issue by damonchen** [hashicorp/terraform-ls#79]
### Server Version

```
v0.1.0-dev
```

### Terraform Version

```
Terraform v0.12.24
```

### Client Version

```

```

### Terraform Configuration Files

```hcl

```

### Expected Behavior

```
const ctxTfSchemaReader = "ctxTerraformSchemaReader"
```

### Actual Behavior

code of: 

https://github.com/hashicorp/terraform-ls/blob/b2cb05503b2d5287da52f39c318ac7c4a266c839/internal/context/context.go#L116

is  be `ctxTerraformSchemaWriter` ?

**Comment by radeksimko** [comment]
Hi @damonchen 
can you be a bit more specific about what exactly isn't working and how could we reproduce the issue?

**Comment by radeksimko** [comment]
Just to clarify - we should certainly fix the wrong context key and also stop using string-based keys for this exact reason (conflicts), but I was just curious if you found this bug by reading the code or if it caused you any real issues at runtime?
