### ISSUE TITLE
Different semantic tokens for invalid references

### ISSUE THREAD

**Issue by dbanck** [hashicorp/terraform-ls#805]
After updating the highlighting of constant keywords in https://github.com/hashicorp/vscode-terraform/issues/944, semantic tokens should take care of highlighting broken references.

### Use-cases
It would be helpful to get feedback when referencing a not-defined variable (or similar item). 

![CleanShot 2022-02-15 at 17 54 09](https://user-images.githubusercontent.com/45985/154111122-4d0eda33-4b02-4dbd-b8e9-3035090c9d54.png)

### Proposal
Instead of highlighting the `var` keyword differently (see screenshot above), it is proposed to change the highlighting of the reference name. In the example above, `non_existing` should be highlighted differently.

**Comment by Rabattkarte** [comment]
> Instead of highlighting the var keyword differently (see screenshot above), it is proposed to change the highlighting of the reference name. In the example above, non_existing should be highlighted differently.

Other plugins (in this case Azure ARM Tools) do it with a squiggly underline like seen in the screenshot:

![CleanShot 2022-02-25 at 08 13 58@2x](https://user-images.githubusercontent.com/16440184/155671425-f23e1af0-8da7-498d-b3ac-1e52593b3e58.png)

Some decoration like this screams at a user: "There's a problem!", personally I like this and see this behavior in multiple plugins.

**Comment by radeksimko** [comment]
@Rabattkarte Yes, this looks like diagnostics and we plan to do this via diagnostics. I think the question here was whether we could _also_ leverage the semantic highlighting.

In retrospect - maybe it's stretching what semantic highlighting is designed for - at least with the current feature set. I'm assuming that diagnostics are pretty much always supported by the client - as it's quite an essential part of LSP - so maybe we just end up adding that to the list in https://github.com/hashicorp/hcl-lang/issues/57

**Comment by jpogran** [comment]
The only method syntax/semantic tokens have to indicate 'invalid' is a red color which, in addition to being problematic for color-blind users, does not give any information for *why* it's invalid. We won't be able to do squiggly lines or text to say why the thing is incorrect.

This is truly where diagnostic warning and errors shine, so the effort is better spent in https://github.com/hashicorp/hcl-lang/issues/57

**Comment by radeksimko** [comment]
I'm going to close this issue as there's nothing we can immediately in terms of semantic highlighting do and it's also unclear whether we should. https://github.com/hashicorp/hcl-lang/issues/57 covers alternative solution involving diagnostics.

On the note of the clarity I opened https://github.com/microsoft/language-server-protocol/issues/1415 upstream
