### ISSUE TITLE
Store diagnostics in memdb table

### ISSUE THREAD

**Issue by dbanck** [hashicorp/terraform-ls#856]
This is part of https://github.com/hashicorp/vscode-terraform/issues/635

### Problem Statement

Currently we're sourcing and publishing diagnostics in two different places:

As result of parsing files
https://github.com/hashicorp/terraform-ls/blob/f246688a37b8edaeb3c36bf536858fd73936d176/internal/langserver/handlers/hooks_module.go#L144-L152

`terraform validate`
https://github.com/hashicorp/terraform-ls/blob/f246688a37b8edaeb3c36bf536858fd73936d176/internal/langserver/handlers/command/validate.go#L67-L72

This can lead to stale or suddenly disappearing diagnostics, for example when `validate` is executed as an editor command.

### Requirements Summary

* Central storage for diagnostics
* Different sources feed diagnostics for a single or multiple files
* Publishing diagnostics will always return all available diagnostics
* Diagnostics need to be refreshed, independent of each other, and not impact or clear other sources

### Proposal

* Create a new memdb table for diagnostics based on the following struct
```go
type Diagnostic struct {
   Dir      string
   Filename string
   Range    hcl.Range
   Severity hcl.DiagnosticSeverity
 
   // The diagnostic's code, which might appear in the user interface
   // e.g. "terraform_deprecated_interpolation"
   Code            string
   // An optional property to describe the error code
   CodeDescription string
 
   // A human-readable string describing the source, e.g. "tflint"
   Source  string
   // The diagnostic's message.
   // e.g. "Interpolation-only expressions are deprecated"
   Message string
 
   // Optional data entry field
   Data interface{}
}
```
* Store HCL diagnostics in the table
* Store `validate` diagnostics in the table
* Query diagnostics table when publishing diagnostics

### Related LSP methods

* [textDocument/publishDiagnostics](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_publishDiagnostics)

### Upcoming diagnostics sources

* https://github.com/hashicorp/vscode-terraform/issues/720
* https://github.com/hashicorp/terraform-ls/issues/334

### Open Questions

* Could memdb "watchers" be used to publish diagnostics?

**Comment by radeksimko** [comment]
@jpogran & @dbanck will take a look if we could avoid storing diagnostics in memdb entirely

James expects the LSP spec to differ from the reality in VS Code and/or other clients.

**Comment by radeksimko** [comment]
I have not looked into gopls codebase for the implementation and current state, but at least last year in 2021 they stored diagnostics per files according to this https://github.com/microsoft/language-server-protocol/issues/1217

**Comment by dbanck** [comment]
It's no longer needed due to #1667 and the diagnostic source map we introduced as part of the enhanced validation work.
