### ISSUE TITLE
Completion of module `source` and `version` from Terraform Registry

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#869]
## Background

Module `source`s are not always easy to get right and often times these are copy-pasted, or typed manually (which increases the risk of typos). Either way the user would benefit from some extra help there.

```hcl
module "example" {
  source = # HERE
}
```

## Expected User Experience

See https://github.com/hashicorp/vscode-terraform/issues/672

### `hashicorp/hcl-lang`

 - [x] https://github.com/hashicorp/terraform-ls/issues/868

### `hashicorp/terraform-schema`

 - [x] Set `CompletionHooks` for `module` `source` to `CompleteRegistryModuleSources` & `CompleteLocalModuleSources`
 - [x] https://github.com/hashicorp/terraform-ls/issues/882
 - [x] Update `earlydecoder` & `module.Meta` to obtain and track each module call's `*hcl.Range` within [`module.Meta`](https://pkg.go.dev/github.com/hashicorp/terraform-schema@v0.0.0-20220411091151-3d46c0c638f0/module#Meta) so that the completion hook for `version` has enough context
 - [x] Set `CompletionHooks` for `module` `version` to `CompleteRegistryModuleVersions`

### `hashicorp/terraform-ls`

 - [x] Store updated `module.Meta` as above in state https://github.com/hashicorp/terraform-ls/blob/687a81be537d83148a70399f14d9462646091395/internal/state/module.go#L18-L26
 - [x] Expose ranges of module calls via `Meta` of `PathContext` to allow `CompleteRegistryModuleVersions` to establish which module source it should provide versions for
 - [x] Introduce `CompleteRegistryModuleSources` completion hook to return addresses of modules from the Registry/Algolia
 - [x] Introduce `CompleteLocalModuleSources` completion hook to return paths of all indexed modules (relative to where they're being called from)
 - [x] Introduce `CompleteRegistryModuleVersions` completion hook to return versions of a given Registry module from the Registry
 - [x] Register `CompleteRegistryModuleSources`, `CompleteLocalModuleSources` and `CompleteRegistryModuleVersions` to the `DecoderContext` https://github.com/hashicorp/terraform-ls/blob/f49cd995e98d242914d7765bd0e0911605ee8405/internal/decoder/decoder.go#L82-L85
 - [ ] Track usage of hooks (especially `CompleteRegistryModuleSources`)

## Implementation Notes

 - Registry Search can be done via Algolia
   - Algolia Go SDK: https://github.com/algolia/algoliasearch-client-go
   - https://www.algolia.com/doc/api-reference/api-methods/search/#examples
   - Example code snippet: https://gist.github.com/radeksimko/0e0a444e6f202b96b9ca63f59dd1e689
   - relevant index is `tf-registry:prod:modules`, relevant App ID & API key is in team 1Password although realistically we'll end up just baking it into the source code and none of it is secret per se
 - Lookup of required module inputs can be done via Registry API v1
   - `https://registry.terraform.io/v1/modules/{FULL_NAME}`
   - e.g. `curl 'https://registry.terraform.io/v1/modules/terraform-aws-modules/vpc/aws' | jq '.root.inputs[] | select(.required == true)'`
 - Lookup of module versions can be done via Registry API
   - Either v2 `https://registry.terraform.io/v2/modules/{MODULE_ID}?include=module-versions`, e.g. https://registry.terraform.io/v2/modules/1143?include=module-versions
   - Or v1 `https://registry.terraform.io/v1/modules/{FULL_NAME}`, e.g. `curl 'https://registry.terraform.io/v1/modules/terraform-aws-modules/vpc/aws' | jq '.versions'`

**Comment by dbanck** [comment]
I've created  #1029 as follow-up ticket for resolving module inputs and removed it from the scope above.

**Comment by dbanck** [comment]
This feature was released with the `0.29.0` release.
