### ISSUE TITLE
Support for textDocument/hover

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-ls#87]
It would be nice to get resource/data source/block/attribute information on hover, required/optional/read-only, typing, description, etc.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover

**Comment by radeksimko** [comment]
As mentioned in https://github.com/hashicorp/terraform-ls/issues/191 it would be useful to show variable values on hover at some point (when we actually support variables and parse them).

**Comment by radeksimko** [comment]
General hover capability was added in 0.10.0 and will be improved over time, #191 tracks hover for references, so I'm going to close this one.
