### ISSUE TITLE
Extract module address parsing logic

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#877]
## Background

We have https://github.com/hashicorp/terraform-registry-address which handles parsing and internal representation of the parsed provider addresses in this codebase and `terraform-schema`.

We need to also parse and represent module addresses in increasingly more places:

 - https://github.com/hashicorp/terraform-ls/pull/872
 - https://github.com/hashicorp/terraform-schema/pull/103
 - https://github.com/hashicorp/terraform-ls/issues/599

## Proposal

Look into Terraform Core's codebase and try to extract the logic which is responsible for parsing the module source from there into https://github.com/hashicorp/terraform-registry-address - presumably as `ParseModuleSourceString` or similar.

--- 

Related: https://github.com/hashicorp/terraform/pull/28338

**Comment by dbanck** [comment]
Closed via https://github.com/hashicorp/terraform-registry-address/pull/7 and https://github.com/hashicorp/terraform-ls/pull/891
