### ISSUE TITLE
More Providers for Auto-Completion

### ISSUE THREAD

**Issue by juliosueiras** [hashicorp/terraform-ls#90]
Hi, just came here to say if you guys want to use my completion data from https://github.com/juliosueiras/vim-terraform-completion under provider_json

P.S. terraform docs has a bad habit of missing content(especially attributes)

**Comment by radeksimko** [comment]
The completion data will be provided to all extensions (including the VSCode one) by the language server and the server will in turn gather this data from the schema via `terraform providers schema` from providers directly.

This allows us to support any provider, even those which may be internal to end-users, and it makes the design a little more maintainable, as we don't have to maintain `(provider) * (version)` copies of completion data anywhere as these will be obtained on demand.

> terraform docs has a bad habit of missing content(especially attributes)

You are right that docs can be outdated at times, which is just another (unintended) effect of schema being under-utilized.

That is something we can address on a few fronts.

 - encourage provider developers to use the existing `Description` mechanism, as opposed to leaving it empty/undefined
   - the fact that LS will leverage schema is one way of doing this 😄 
   - we will offer some mechanisms to generate docs (semi)-automatically from the schema, at which point the argument of duplication will no longer be valid and the schema will become the single point of truth for the important metadata
   - eventually (in the far future) we may even deprecate the whole concept of hand-crafted docs
 - expose more schema metadata via [the JSON format](https://www.terraform.io/docs/commands/providers/schema.html#providers-schema-representation) that can be leveraged both in rendered documentation and LS (and in turn IDEs) - e.g.:
   - deprecations
   - default values
   - possible values - such as EC2 instance types for `aws_instance`
   - validation rules (this may be tricky to expose in a machine-readable form)

Either way the latest release of the LS here already satisfies the spirit of what's being asked for (more providers), so I'm going to close it.
