### ISSUE TITLE
`module.providers` returns no providers when `required_providers` has incomplete address

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#906]
### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    name = {
      source = "hashicorp/"
    }
    aws = {
      source = "hashicorp/aws"
    }
  }
}
```

### Log Output

```
2022/05/03 06:17:09 rpc_logger.go:29: Incoming request for "workspace/executeCommand" (ID 345): {"command":"terraform-ls.module.providers","arguments":["uri=file:///private/var/workspace/tf-test"]}
2022/05/03 06:17:09 rpc_logger.go:50: Response to "workspace/executeCommand" (ID 345): {"v":0,"provider_requirements":{},"installed_providers":{}}
```

### Expected Behavior

`aws` provider requirement to be returned and incomplete requirement to be either ignored or somehow represented as incomplete.

### Actual Behavior

No providers are returned.

![Screenshot 2022-05-03 at 06 20 46](https://user-images.githubusercontent.com/287584/166407611-8721d27a-726f-400b-8609-81151e7e217b.png)

### Steps to Reproduce

1. Open an empty module and paste the configuration above into VS Code TF extension
2. See the module provider view or check the log

**Comment by jpogran** [comment]
I think this is fixed by removing the filter for returned providers, like I did in https://github.com/hashicorp/vscode-terraform/pull/1084
