### ISSUE TITLE
Add resource name suggestions to the template

### ISSUE THREAD

**Issue by dcosson** [hashicorp/terraform-ls#91]
It would be great if the resource names autocompleted. There is another extension Terraform Autocomplete that does this well:

![screen shot 2018-10-17 at 2 26 12 pm](https://user-images.githubusercontent.com/708904/47117399-14d02200-d219-11e8-9901-433b5d0e3074.png)

But, otherwise the functionality in this vscode-terraform is much more full-featured so I would prefer to stick with this one. The two extensions also conflict a bit so it doesn't work very well to have both installed.

**Comment by radeksimko** [comment]
This was added to the language server in `v0.2.0` and will become available automatically in the upcoming release of VSCode as [per our blog post](https://www.hashicorp.com/blog/supporting-the-hashicorp-terraform-extension-for-visual-studio-code/).

There is a few caveats to mention:

 - for some editors - and I'm unsure whether/how this affects VSCode - we may be returning too many completion items in case of big providers like AWS - this is tracked under https://github.com/hashicorp/terraform-ls/issues/12
 - the completion won't work in case the declaration is invalid (e.g. `resource ""` without the curly braces) - this is tracked under https://github.com/hashicorp/terraform-ls/issues/57

and here is a few related issues:

 - references to resources (and other blocks) are tracked under https://github.com/hashicorp/terraform-ls/issues/38
 - completion of `resource` keyword itself, and all other 1st-level keywords is tracked under https://github.com/hashicorp/terraform-ls/issues/18

In case there is any other completion related issue which I didn't mention above or isn't in the tracker already I'd welcome you to [open a new one](https://github.com/hashicorp/terraform-ls/issues/new/choose).
