### ISSUE TITLE
no autocomplete on previous resources inputs, attributes etc.

### ISSUE THREAD

**Issue by cmeyertons** [hashicorp/terraform-ls#92]
when i back reference a previous resource in the same module, i don't get any intellisense about that resource.  if i'm not sure about something i have to go to the resources docs, which is a sub-optimal experience.

![image](https://user-images.githubusercontent.com/19917677/47784583-05021480-dcd4-11e8-959a-6c279cd33058.png)

**Comment by radeksimko** [comment]
The completion of references will be handled by the language server as part of https://github.com/hashicorp/terraform-ls/issues/38 so I'd recommend subscribing to that issue.

With that said I'm not fully convinced if the completion will work the way you're suggesting.

#12 suggests that the server should not be returning _all_ possible candidates, but instead return a limited number of candidates (say <100) and pick these based on what is relevant - e.g. filter items based on what was already written. So in your case you already wrote `node` which matches exactly 1 completion candidate, so we would probably display just that one candidate. Probably still better UX than just "No suggestions"? Alternatively we'd have to treat 100% match as no match and I'm not sure what UX side effects this may have.

Also the tricky thing here is that we'd need to calculate the byte range to replace with the confirmed candidate. Not impossible, just requires some extra effort. i.e. we need to make sure that when you'd `Ctrl+Space` anywhere in `node` and picked `dns_prefix` then we'd replace `node` with `dns_prefix`, and avoid just inserting `dns_prefix` in the middle of `node`.

--- 

Do you reckon it would be a lot of trouble if you were forced to `<Backspace>` a few times to get more completion candidates?

**Comment by radeksimko** [comment]
Initial support for references was added in (now merged) https://github.com/hashicorp/terraform-ls/pull/485 which will be released in coming days. The same PR also includes some description of features added and links to follow-up issues covering features which were omitted from that initial PR.

With that in mind I'm going to close this issue - keep an eye out for the upcoming update (0.17.0).
