### ISSUE TITLE
Semantic Token Type highlighting

### ISSUE THREAD

**Issue by chris3ware** [hashicorp/terraform-ls#921]
### Server Version

```
0.27.0
```

### Terraform Version

```
v1.0.2
```

### Client Version

```
VSCode 1.67.1
```

### Terraform Configuration Files

```hcl
resource "aws_cloudtrail" "this"
```

### Log Output

[Logs](https://gist.github.com/chris3ware/674c69736c7678468cc4633ac425dca3)

### Expected Behaviour
Following #803 I believe the resource block type and resource block name should be different colours based on the semantic token types as shown in [710](https://github.com/hashicorp/vscode-terraform/issues/710)

### Actual Behaviour
The resource block type and block label are the same colour. See screenshots below:

<img width="1043" alt="Screenshot 2022-05-17 at 13 47 21" src="https://user-images.githubusercontent.com/36608309/168818249-a6f62429-acf2-42cd-8884-643976a5a98d.png">

<img width="1094" alt="Screenshot 2022-05-17 at 13 47 33" src="https://user-images.githubusercontent.com/36608309/168818335-a2b4ea69-01ae-411b-a5e0-b033c4737fd4.png">

### Steps to Reproduce

I am running MacOS 10.15.7 and the [Gruvbox Material](https://marketplace.visualstudio.com/items?itemName=sainnhe.gruvbox-material) theme.

**Comment by radeksimko** [comment]
Hi @chris3ware 
Most themes generally work with a limited set of default token types and modifiers. The changes you linked to _enables_ theme maintainers to assign different colours, but we don't distribute any themes ourselves, which would make use of these custom token types or modifiers.

Theme maintainers (including `Gruvbox Material`) are however welcomed to assign any colours they wish to the custom types and modifiers, which we have also documented here:
https://github.com/hashicorp/terraform-ls/blob/main/docs/syntax-highlighting.md#custom-theme-support

In your particular examples the theme would hook up `hcl-blockLabel.terraform-resource.terraform-type` to have different colour from `hcl-blockLabel.terraform-resource.terraform-name`.

Does that help clear out any confusion?

**Comment by chris3ware** [comment]
Hi, yes it does. Thanks for the quick response.
