### ISSUE TITLE
Unable to format file. Error: "Malformated version:"

### ISSUE THREAD

**Issue by Sergey-Kirgizov** [hashicorp/terraform-ls#944]
### Server Version
installed by hombrew and reported by hombrew as v. 0.28.0
```
0.0.0-dev
platform: darwin/arm64
go: go1.18.3
compiler: gc
```

### Terraform Version
```
Terraform v1.2.2
on darwin_arm64
```

### Client Version
```
VSCode 
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z (3 wks ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```

### Terraform Configuration Files

```
terraform {
  backend "s3" {
    encrypt            = true
    region         = "us-east-1"
    key            = "some/key"
    bucket         = "some-bucket-name"
    dynamodb_table = "some-table-name"
  }
}
```

### Log Output

```
2022/06/08 21:03:23 rpc_logger.go:29: Incoming request for "textDocument/formatting" (ID 31): {"textDocument":{"uri":"file:///**********/backend.tf"},"options":{"tabSize":2,"insertSpaces":true}}
2022/06/08 21:03:23 formatting.go:30: formatting document via "/opt/homebrew/bin/terraform-ls"
2022/06/08 21:03:24 rpc_logger.go:45: Error for "textDocument/formatting" (ID 31): [-32098] fmt was first introduced in Terraform 0.7.7: unable to parse version "": Malformed version: 
2022/06/08 21:03:24 opts.go:218: Completed 1 requests [286.330583ms elapsed]
[Error - 21:03:24] Request textDocument/formatting failed.
  Message: fmt was first introduced in Terraform 0.7.7: unable to parse version "": Malformed version: 
  Code: -32098 
2022/06/08 21:03:24 opts.go:218: Received request batch of size 1 (qlen=0)
2022/06/08 21:03:24 opts.go:218: Dequeued request batch of length 1 (qlen=0)
2022/06/08 21:03:24 rpc_logger.go:29: Incoming notification for "textDocument/didSave": {"textDocument":{"uri":"file://***************/backend.tf"}}
2022/06/08 21:03:24 opts.go:218: Discarding error from notification to "textDocument/didSave": terraform validate -json was added in 0.12.0: unable to parse version "": Malformed version:
```

### Expected Behavior
Formating performed

### Actual Behavior
nothing changed

### Steps to Reproduce
Open file
add some spaces before "=" sign
save file

**Comment by jpogran** [comment]
Thank you for the detailed report @Sergey-Kirgizov. I see you have installed terraform-ls 0.28.0 via homebrew but it's showing up as 0.0.0. 

Skipping that for a moment, if you are using VS Code you do not need to install terraform-ls separately, it comes bundled with the Terraform Extension. Installing the Terraform Extension will have put the terraform-ls binary in the proper place, and keep it up to date as new releases are out. If you uninstall the homebrew version and ensure your VS Code settings don't have `terraform.languageServer.pathToBinary` set you will use the bundled version and not have to install things yourself.

As for the Terraform version error, this looks like it's finding the wrong executable in your PATH. You have Terraform 1.2.2 installed, but the error messages imply there is a version less than 0.7 on your machine. When we activate, we look for the Terraform binary on PATH, so if there isn't a binary found or the wrong one found first you will encounter problems. Can you confirm there are no other installations present?

**Comment by Sergey-Kirgizov** [comment]
Hi @jpogran!

Thank you for reply! 

The exclusion of ```terraform.languageServer.pathToBinary``` from settings.json completely resolved my problem.  Now formatting works like a charm!

**Comment by radeksimko** [comment]
Glad you got it sorted.

Based on the log though I would say the root cause was more likely `terraform-ls.terraformExecPath` pointing to the language server, as opposed to Terraform CLI. Similar to `pathToBinary`, this option can generally be left unset/default and LS will discover Terraform CLI automatically. Instead what happened there was that language server was trying to execute itself in order to format a document and that binary also returned `0.0.0` which confused version detection assuming `version` output from Terraform, not LS.

I think there are two things we could do to help avoid similar situation in the future
 - Ensure the community-maintained Homebrew formula is built with the right version and does not default to `0.0.0`
 - Show warning or error when we detect that `terraformExecPath` points to `terraform-ls`

**Comment by radeksimko** [comment]
I would also add that we (HashiCorp) maintain our own [Homebrew tap](https://github.com/hashicorp/homebrew-tap), which we recommend folks to use. Formulas installed through that tap reflect each product's intended build process - including building binaries with the right ldflags such as version, building against the right Go version etc. and they're also code-signed binaries, allowing for verification per [these instructions](https://www.hashicorp.com/security#code-signature-verification).

The community maintained formulae from `homebrew/homebrew-core` may not always use the correct build process and are not signed. This may be an unfortunate effect of Go not having any particular way of codifying build instructions, not necessarily Homebrew's fault.
