### ISSUE TITLE
Error when a symlink with ".tfvars" extension is created inside a workspace

### ISSUE THREAD

**Issue by divergentdave** [hashicorp/terraform-ls#957]
### Extension

```
v2.23.0
```

### VS Code
```
1.68.1
```

### Operating System
```
Ubuntu 20.04.4 LTS
```

### Terraform Version
```
Terraform v1.2.3
on linux_amd64
```

### Steps To Reproduce
Create a valid symlink with a filename that ends in `.tfvars` while VS Code is open, in a directory that it is watching.

### Expected Behavior
No error or warning.

### Actual Behavior
A notification that says "Unable to update "/path/to/.current_environment.auto.tfvars": filetype not supported. This is likely a bug which should be reported."
 
### Additional context
I have tooling in my project that creates a symlink with an `.auto.tfvars` extension, pointing to a `.tfvars` file. (The Terraform CLI has worked fine with this setup) Whenever this symlink is recreated, I see a notification in VS Code with the above error.

**Comment by radeksimko** [comment]
@divergentdave I tried to reproduce this without much luck. The logic seems to be working as expected in that even symlinks get reflected correctly in my local environment (macOS Monterey 12.4, Apple M1 Pro, Extension `v2.23.0`).

https://user-images.githubusercontent.com/287584/175526167-73451e6d-810c-4071-8f3a-73e83c96de9a.mov

Full repro steps I tried:

```hcl
variable "alpha" {
  type = string
}

variable "beta" {
  type = number
}

output "example" {
  value = "${var.alpha} / ${var.beta}"
}
```
**`test.tfvars`** (one level above the VS Code workspace)
```hcl
alpha = "foobar"
beta  = 42
```
_within the VS Code workspace_
```
ln -s ../test.tfvars ./terraform.tfvars
```

--- 

Is there any chance the notifications show a different file? If not - could you provide a repro case as a sequence of steps, and/or possibly recording?

Thanks!

**Comment by radeksimko** [comment]
Could you also provide any (custom) settings you have set for the Terraform extension? It _shouldn't_ matter as the extension controls what files are watched internally, but it would be helpful just in case there's something different between our environments.

**Comment by radeksimko** [comment]
As an aside - I can believe that there is possibly a bug involving symlinks, I also filed https://github.com/hashicorp/terraform-ls/issues/241 some time ago and I'm aware that we don't evaluate symlinks in various places, but I still wasn't able to come up with any repro case that would demonstrate any particular bug.

**Comment by divergentdave** [comment]
I don't have any non-default extension settings configured. I have extension version v2.23.0 installed as well. Here's a minimal reproduction, as a bash script, with a screen recording of it in action. It seems that the leading `.` in the link name is required for reproduction, as well as the directory layout. I wonder if our differing operating systems could be part of the cause as well.

```bash
#!/bin/bash
echo 'terraform {}' > main.tf
echo 'a = 1' > vars.tfvars
mkdir dir
code .
read -s -p "Press enter to continue..." ; echo
ln -s ../vars.tfvars dir/.link.tfvars
```

https://user-images.githubusercontent.com/181772/175530987-d48bd4bc-ed17-4382-9140-880fcede592e.mp4

**Comment by radeksimko** [comment]
Reproduced! Thank you for the prompt response with repro steps - these helped.

![Screenshot 2022-06-24 at 13 26 59](https://user-images.githubusercontent.com/287584/175535373-b057dff7-cc7c-4fae-9135-191312382d0f.png)

I will dig further to see what's causing it.

**Comment by radeksimko** [comment]
I think I found the culprit

https://github.com/hashicorp/terraform-ls/blob/000cb538ca2325e8e7f7c8d1da86b3ea411942ba/internal/terraform/ast/variables.go#L21

https://github.com/hashicorp/terraform-ls/blob/000cb538ca2325e8e7f7c8d1da86b3ea411942ba/internal/terraform/ast/ast.go#L9-L10

**Comment by radeksimko** [comment]
Fix now pending review in https://github.com/hashicorp/terraform-ls/pull/968
