### ISSUE TITLE
Language server crashes when using azure storage account blob container in vscode workspace

### ISSUE THREAD

**Issue by TeamDman** [hashicorp/terraform-ls#959]
### Server Version

```
0.28.1
```

### Terraform Version

```
Terraform v1.2.3
on windows_amd64
```

### Client Version

VSCode

![image](https://user-images.githubusercontent.com/9356891/174462226-a026c14d-6a73-4165-9c2e-4719f9fd360f.png)

Azure Storage extension
v0.14.1

### Terraform Configuration Files

an empty "a.tf" file can reproduce

### Log Output

https://gist.github.com/TeamDman/3d8684494d05b2a3f098410da395ee6c

### Expected Behavior

no crash

### Actual Behavior

crash

### Steps to Reproduce

1. Add azure storage extension
2. use azure tab in vscode to find a storage account blob container and add it to your workspace so you have a local folder open with an empty .tf file and you also have the storage account blob container open
3. Terraform language server stops working

**Comment by radeksimko** [comment]
We have fixed the crash as part of https://github.com/hashicorp/terraform-ls/pull/969 - so the next release should only raise warnings, but more importantly the next release of the VS Code extension (v2.24.0) and latest preview version should not be sending URIs like these to the language server at all. This was addressed as part of https://github.com/hashicorp/vscode-terraform/pull/1163

You can either wait for these next releases, or try out the preview in the meantime:
https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform-preview
