### ISSUE TITLE
Autocomplete in the expression token "${}"

### ISSUE THREAD

**Issue by slideroh** [hashicorp/terraform-ls#974]
### Current Version

```
Latest extension: HashiCorp Terraform v2.23.0
```
### Use-cases
I would like to work better and faster, in this case I'd like to use autocomplete/intelisense with expression token `"${}"`. Just to achieve something like the value from variable + individual text, like name-lb which is "${var.name}-lb".

### Attempted Solutions
```
resource "azurerm_lb" "lb2" {
  location = "value"
  name = "${var.autocomplete-does-not-appear}"  # type inside "${}" var [dot]
  resource_group_name = "value"
}
```
![var_inside_expression_token](https://user-images.githubusercontent.com/22775364/176059410-d25b7b2e-f969-4729-a12b-d4c450d0b4fb.png)

### Proposal

I would like to see autocomplete inside the express token.
Like on the screenshot below, which is outside/without ${} token
![var_without_expression_token](https://user-images.githubusercontent.com/22775364/176059475-e6d442fc-2c84-41b7-a523-e42d29de032b.png)

### Related LSP methods

textDocument.completion
### References

--

I would also like to see an autocomplete feature when entering data such as sku/access_tier, as it works in Bicep. I know this is unrelated and a completely different topic, but I haven't found one.
Just example:
Autocomplete for access_tier:
- Bicep
![autocomplete-storage-bicep](https://user-images.githubusercontent.com/22775364/176060100-f8ef7e36-e907-4ff3-ae10-dc29b6969ea5.png)
- Terraform
![noautocomplete-for_tier](https://user-images.githubusercontent.com/22775364/176060111-5e211953-4845-47b1-a5e6-62ea5f234436.png)
I'd like to know if this is the desired effect, or if I've not initiated something and therefore don't see the hint/autocomplete.

Thank you.
Anyway, you're doing a fantastic job. Just curious, or trying to enhance :)

**Comment by radeksimko** [comment]
Hi @slideroh 
thanks for the suggestion, I believe this is already covered by https://github.com/hashicorp/terraform-ls/issues/522 so I'm going to close this as a duplicate to keep conversation in one place.

btw. we track all the missing expression types under https://github.com/hashicorp/vscode-terraform/issues/641
